// Code generated by go-abi. DO NOT EDIT.

package contracts

import (
	"encoding/binary"
	"errors"
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// counter()
	CounterSelector = [4]byte{0x61, 0xbc, 0x22, 0x1a}
	// deposit()
	DepositSelector = [4]byte{0xd0, 0xe3, 0x0d, 0xb0}
	// ibcTransferAndRevert(string,string,string,uint256,address,string,(uint64,uint64),uint64,string)
	IbcTransferAndRevertSelector = [4]byte{0xe1, 0x2e, 0x9b, 0x27}
	// testIbcTransfer(string,string,string,uint256,address,string,(uint64,uint64),uint64,string)
	TestIbcTransferSelector = [4]byte{0xd8, 0xbb, 0x6c, 0x0e}
	// testIbcTransferFromContract(string,string,string,uint256,string,(uint64,uint64),uint64,string)
	TestIbcTransferFromContractSelector = [4]byte{0xbc, 0xc4, 0x5b, 0x79}
	// testIbcTransferWithTransfer(string,string,string,uint256,address,string,(uint64,uint64),uint64,string,bool,bool)
	TestIbcTransferWithTransferSelector = [4]byte{0xc3, 0x52, 0x64, 0x50}
	// testRevertIbcTransfer(string,string,string,uint256,address,string,address,(uint64,uint64),uint64,string,bool)
	TestRevertIbcTransferSelector = [4]byte{0xb4, 0x2b, 0xc5, 0xa9}
)

// Big endian integer versions of function selectors
const (
	CounterID                     = 1639719450
	DepositID                     = 3504541104
	IbcTransferAndRevertID        = 3777927975
	TestIbcTransferID             = 3636161550
	TestIbcTransferFromContractID = 3166985081
	TestIbcTransferWithTransferID = 3276956752
	TestRevertIbcTransferID       = 3022767529
)

const HeightStaticSize = 64

var _ abi.Tuple = (*Height)(nil)

// Height represents an ABI tuple
type Height struct {
	RevisionNumber uint64
	RevisionHeight uint64
}

// EncodedSize returns the total encoded size of Height
func (t Height) EncodedSize() int {
	dynamicSize := 0

	return HeightStaticSize + dynamicSize
}

// EncodeTo encodes Height to ABI bytes in the provided buffer
func (value Height) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := HeightStaticSize // Start dynamic data after static section
	// Field RevisionNumber: uint64
	if _, err := abi.EncodeUint64(value.RevisionNumber, buf[0:]); err != nil {
		return 0, err
	}

	// Field RevisionHeight: uint64
	if _, err := abi.EncodeUint64(value.RevisionHeight, buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes Height to ABI bytes
func (value Height) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Height from ABI bytes in the provided buffer
func (t *Height) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 64
	// Decode static field RevisionNumber: uint64
	t.RevisionNumber, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode static field RevisionHeight: uint64
	t.RevisionHeight, _, err = abi.DecodeUint64(data[32:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*CounterCall)(nil)

// CounterCall represents the input arguments for counter function
type CounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t CounterCall) GetMethodName() string {
	return "counter"
}

// GetMethodID returns the function name
func (t CounterCall) GetMethodID() uint32 {
	return CounterID
}

// GetMethodSelector returns the function name
func (t CounterCall) GetMethodSelector() [4]byte {
	return CounterSelector
}

// EncodeWithSelector encodes counter arguments to ABI bytes including function selector
func (t CounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], CounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const CounterReturnStaticSize = 32

var _ abi.Tuple = (*CounterReturn)(nil)

// CounterReturn represents an ABI tuple
type CounterReturn struct {
	Field1 int64
}

// EncodedSize returns the total encoded size of CounterReturn
func (t CounterReturn) EncodedSize() int {
	dynamicSize := 0

	return CounterReturnStaticSize + dynamicSize
}

// EncodeTo encodes CounterReturn to ABI bytes in the provided buffer
func (value CounterReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := CounterReturnStaticSize // Start dynamic data after static section
	// Field Field1: int64
	if _, err := abi.EncodeInt64(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes CounterReturn to ABI bytes
func (value CounterReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CounterReturn from ABI bytes in the provided buffer
func (t *CounterReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: int64
	t.Field1, _, err = abi.DecodeInt64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*DepositCall)(nil)

// DepositCall represents the input arguments for deposit function
type DepositCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t DepositCall) GetMethodName() string {
	return "deposit"
}

// GetMethodID returns the function name
func (t DepositCall) GetMethodID() uint32 {
	return DepositID
}

// GetMethodSelector returns the function name
func (t DepositCall) GetMethodSelector() [4]byte {
	return DepositSelector
}

// EncodeWithSelector encodes deposit arguments to ABI bytes including function selector
func (t DepositCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DepositSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// DepositReturn represents the input arguments for deposit function
type DepositReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*IbcTransferAndRevertCall)(nil)

const IbcTransferAndRevertCallStaticSize = 320

var _ abi.Tuple = (*IbcTransferAndRevertCall)(nil)

// IbcTransferAndRevertCall represents an ABI tuple
type IbcTransferAndRevertCall struct {
	SourcePort       string
	SourceChannel    string
	Denom            string
	Amount           *big.Int
	Sender           common.Address
	Receiver         string
	TimeoutHeight    Height
	TimeoutTimestamp uint64
	Memo             string
}

// EncodedSize returns the total encoded size of IbcTransferAndRevertCall
func (t IbcTransferAndRevertCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.SourcePort)
	dynamicSize += abi.SizeString(t.SourceChannel)
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += abi.SizeString(t.Receiver)
	dynamicSize += abi.SizeString(t.Memo)

	return IbcTransferAndRevertCallStaticSize + dynamicSize
}

// EncodeTo encodes IbcTransferAndRevertCall to ABI bytes in the provided buffer
func (value IbcTransferAndRevertCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := IbcTransferAndRevertCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field SourcePort: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourcePort, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field SourceChannel: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourceChannel, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[96:]); err != nil {
		return 0, err
	}

	// Field Sender: address
	if _, err := abi.EncodeAddress(value.Sender, buf[128:]); err != nil {
		return 0, err
	}

	// Field Receiver: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Receiver, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field TimeoutHeight: (uint64,uint64)
	if _, err := value.TimeoutHeight.EncodeTo(buf[192:]); err != nil {
		return 0, err
	}

	// Field TimeoutTimestamp: uint64
	if _, err := abi.EncodeUint64(value.TimeoutTimestamp, buf[256:]); err != nil {
		return 0, err
	}

	// Field Memo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[288+24:288+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Memo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes IbcTransferAndRevertCall to ABI bytes
func (value IbcTransferAndRevertCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes IbcTransferAndRevertCall from ABI bytes in the provided buffer
func (t *IbcTransferAndRevertCall) Decode(data []byte) (int, error) {
	if len(data) < 320 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 320
	// Decode dynamic field SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourcePort")
		}
		t.SourcePort, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourceChannel")
		}
		t.SourceChannel, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Denom
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Denom")
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field Sender: address
	t.Sender, _, err = abi.DecodeAddress(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Receiver
	{
		offset := int(binary.BigEndian.Uint64(data[160+24 : 160+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Receiver")
		}
		t.Receiver, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field TimeoutHeight: (uint64,uint64)
	_, err = t.TimeoutHeight.Decode(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field TimeoutTimestamp: uint64
	t.TimeoutTimestamp, _, err = abi.DecodeUint64(data[256:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Memo
	{
		offset := int(binary.BigEndian.Uint64(data[288+24 : 288+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Memo")
		}
		t.Memo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t IbcTransferAndRevertCall) GetMethodName() string {
	return "ibcTransferAndRevert"
}

// GetMethodID returns the function name
func (t IbcTransferAndRevertCall) GetMethodID() uint32 {
	return IbcTransferAndRevertID
}

// GetMethodSelector returns the function name
func (t IbcTransferAndRevertCall) GetMethodSelector() [4]byte {
	return IbcTransferAndRevertSelector
}

// EncodeWithSelector encodes ibcTransferAndRevert arguments to ABI bytes including function selector
func (t IbcTransferAndRevertCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], IbcTransferAndRevertSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const IbcTransferAndRevertReturnStaticSize = 32

var _ abi.Tuple = (*IbcTransferAndRevertReturn)(nil)

// IbcTransferAndRevertReturn represents an ABI tuple
type IbcTransferAndRevertReturn struct {
	NextSequence uint64
}

// EncodedSize returns the total encoded size of IbcTransferAndRevertReturn
func (t IbcTransferAndRevertReturn) EncodedSize() int {
	dynamicSize := 0

	return IbcTransferAndRevertReturnStaticSize + dynamicSize
}

// EncodeTo encodes IbcTransferAndRevertReturn to ABI bytes in the provided buffer
func (value IbcTransferAndRevertReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := IbcTransferAndRevertReturnStaticSize // Start dynamic data after static section
	// Field NextSequence: uint64
	if _, err := abi.EncodeUint64(value.NextSequence, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes IbcTransferAndRevertReturn to ABI bytes
func (value IbcTransferAndRevertReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes IbcTransferAndRevertReturn from ABI bytes in the provided buffer
func (t *IbcTransferAndRevertReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field NextSequence: uint64
	t.NextSequence, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TestIbcTransferCall)(nil)

const TestIbcTransferCallStaticSize = 320

var _ abi.Tuple = (*TestIbcTransferCall)(nil)

// TestIbcTransferCall represents an ABI tuple
type TestIbcTransferCall struct {
	SourcePort       string
	SourceChannel    string
	Denom            string
	Amount           *big.Int
	Sender           common.Address
	Receiver         string
	TimeoutHeight    Height
	TimeoutTimestamp uint64
	Memo             string
}

// EncodedSize returns the total encoded size of TestIbcTransferCall
func (t TestIbcTransferCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.SourcePort)
	dynamicSize += abi.SizeString(t.SourceChannel)
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += abi.SizeString(t.Receiver)
	dynamicSize += abi.SizeString(t.Memo)

	return TestIbcTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TestIbcTransferCall to ABI bytes in the provided buffer
func (value TestIbcTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestIbcTransferCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field SourcePort: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourcePort, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field SourceChannel: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourceChannel, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[96:]); err != nil {
		return 0, err
	}

	// Field Sender: address
	if _, err := abi.EncodeAddress(value.Sender, buf[128:]); err != nil {
		return 0, err
	}

	// Field Receiver: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Receiver, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field TimeoutHeight: (uint64,uint64)
	if _, err := value.TimeoutHeight.EncodeTo(buf[192:]); err != nil {
		return 0, err
	}

	// Field TimeoutTimestamp: uint64
	if _, err := abi.EncodeUint64(value.TimeoutTimestamp, buf[256:]); err != nil {
		return 0, err
	}

	// Field Memo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[288+24:288+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Memo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes TestIbcTransferCall to ABI bytes
func (value TestIbcTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestIbcTransferCall from ABI bytes in the provided buffer
func (t *TestIbcTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 320 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 320
	// Decode dynamic field SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourcePort")
		}
		t.SourcePort, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourceChannel")
		}
		t.SourceChannel, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Denom
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Denom")
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field Sender: address
	t.Sender, _, err = abi.DecodeAddress(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Receiver
	{
		offset := int(binary.BigEndian.Uint64(data[160+24 : 160+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Receiver")
		}
		t.Receiver, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field TimeoutHeight: (uint64,uint64)
	_, err = t.TimeoutHeight.Decode(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field TimeoutTimestamp: uint64
	t.TimeoutTimestamp, _, err = abi.DecodeUint64(data[256:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Memo
	{
		offset := int(binary.BigEndian.Uint64(data[288+24 : 288+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Memo")
		}
		t.Memo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestIbcTransferCall) GetMethodName() string {
	return "testIbcTransfer"
}

// GetMethodID returns the function name
func (t TestIbcTransferCall) GetMethodID() uint32 {
	return TestIbcTransferID
}

// GetMethodSelector returns the function name
func (t TestIbcTransferCall) GetMethodSelector() [4]byte {
	return TestIbcTransferSelector
}

// EncodeWithSelector encodes testIbcTransfer arguments to ABI bytes including function selector
func (t TestIbcTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestIbcTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const TestIbcTransferReturnStaticSize = 32

var _ abi.Tuple = (*TestIbcTransferReturn)(nil)

// TestIbcTransferReturn represents an ABI tuple
type TestIbcTransferReturn struct {
	Field1 uint64
}

// EncodedSize returns the total encoded size of TestIbcTransferReturn
func (t TestIbcTransferReturn) EncodedSize() int {
	dynamicSize := 0

	return TestIbcTransferReturnStaticSize + dynamicSize
}

// EncodeTo encodes TestIbcTransferReturn to ABI bytes in the provided buffer
func (value TestIbcTransferReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestIbcTransferReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint64
	if _, err := abi.EncodeUint64(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestIbcTransferReturn to ABI bytes
func (value TestIbcTransferReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestIbcTransferReturn from ABI bytes in the provided buffer
func (t *TestIbcTransferReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint64
	t.Field1, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TestIbcTransferFromContractCall)(nil)

const TestIbcTransferFromContractCallStaticSize = 288

var _ abi.Tuple = (*TestIbcTransferFromContractCall)(nil)

// TestIbcTransferFromContractCall represents an ABI tuple
type TestIbcTransferFromContractCall struct {
	SourcePort       string
	SourceChannel    string
	Denom            string
	Amount           *big.Int
	Receiver         string
	TimeoutHeight    Height
	TimeoutTimestamp uint64
	Memo             string
}

// EncodedSize returns the total encoded size of TestIbcTransferFromContractCall
func (t TestIbcTransferFromContractCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.SourcePort)
	dynamicSize += abi.SizeString(t.SourceChannel)
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += abi.SizeString(t.Receiver)
	dynamicSize += abi.SizeString(t.Memo)

	return TestIbcTransferFromContractCallStaticSize + dynamicSize
}

// EncodeTo encodes TestIbcTransferFromContractCall to ABI bytes in the provided buffer
func (value TestIbcTransferFromContractCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestIbcTransferFromContractCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field SourcePort: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourcePort, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field SourceChannel: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourceChannel, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[96:]); err != nil {
		return 0, err
	}

	// Field Receiver: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[128+24:128+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Receiver, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field TimeoutHeight: (uint64,uint64)
	if _, err := value.TimeoutHeight.EncodeTo(buf[160:]); err != nil {
		return 0, err
	}

	// Field TimeoutTimestamp: uint64
	if _, err := abi.EncodeUint64(value.TimeoutTimestamp, buf[224:]); err != nil {
		return 0, err
	}

	// Field Memo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[256+24:256+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Memo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes TestIbcTransferFromContractCall to ABI bytes
func (value TestIbcTransferFromContractCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestIbcTransferFromContractCall from ABI bytes in the provided buffer
func (t *TestIbcTransferFromContractCall) Decode(data []byte) (int, error) {
	if len(data) < 288 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 288
	// Decode dynamic field SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourcePort")
		}
		t.SourcePort, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourceChannel")
		}
		t.SourceChannel, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Denom
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Denom")
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Receiver
	{
		offset := int(binary.BigEndian.Uint64(data[128+24 : 128+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Receiver")
		}
		t.Receiver, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field TimeoutHeight: (uint64,uint64)
	_, err = t.TimeoutHeight.Decode(data[160:])
	if err != nil {
		return 0, err
	}
	// Decode static field TimeoutTimestamp: uint64
	t.TimeoutTimestamp, _, err = abi.DecodeUint64(data[224:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Memo
	{
		offset := int(binary.BigEndian.Uint64(data[256+24 : 256+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Memo")
		}
		t.Memo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestIbcTransferFromContractCall) GetMethodName() string {
	return "testIbcTransferFromContract"
}

// GetMethodID returns the function name
func (t TestIbcTransferFromContractCall) GetMethodID() uint32 {
	return TestIbcTransferFromContractID
}

// GetMethodSelector returns the function name
func (t TestIbcTransferFromContractCall) GetMethodSelector() [4]byte {
	return TestIbcTransferFromContractSelector
}

// EncodeWithSelector encodes testIbcTransferFromContract arguments to ABI bytes including function selector
func (t TestIbcTransferFromContractCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestIbcTransferFromContractSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const TestIbcTransferFromContractReturnStaticSize = 32

var _ abi.Tuple = (*TestIbcTransferFromContractReturn)(nil)

// TestIbcTransferFromContractReturn represents an ABI tuple
type TestIbcTransferFromContractReturn struct {
	Field1 uint64
}

// EncodedSize returns the total encoded size of TestIbcTransferFromContractReturn
func (t TestIbcTransferFromContractReturn) EncodedSize() int {
	dynamicSize := 0

	return TestIbcTransferFromContractReturnStaticSize + dynamicSize
}

// EncodeTo encodes TestIbcTransferFromContractReturn to ABI bytes in the provided buffer
func (value TestIbcTransferFromContractReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestIbcTransferFromContractReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint64
	if _, err := abi.EncodeUint64(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestIbcTransferFromContractReturn to ABI bytes
func (value TestIbcTransferFromContractReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestIbcTransferFromContractReturn from ABI bytes in the provided buffer
func (t *TestIbcTransferFromContractReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint64
	t.Field1, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TestIbcTransferWithTransferCall)(nil)

const TestIbcTransferWithTransferCallStaticSize = 384

var _ abi.Tuple = (*TestIbcTransferWithTransferCall)(nil)

// TestIbcTransferWithTransferCall represents an ABI tuple
type TestIbcTransferWithTransferCall struct {
	SourcePort       string
	SourceChannel    string
	Denom            string
	Amount           *big.Int
	Sender           common.Address
	Receiver         string
	TimeoutHeight    Height
	TimeoutTimestamp uint64
	Memo             string
	Before           bool
	After            bool
}

// EncodedSize returns the total encoded size of TestIbcTransferWithTransferCall
func (t TestIbcTransferWithTransferCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.SourcePort)
	dynamicSize += abi.SizeString(t.SourceChannel)
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += abi.SizeString(t.Receiver)
	dynamicSize += abi.SizeString(t.Memo)

	return TestIbcTransferWithTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TestIbcTransferWithTransferCall to ABI bytes in the provided buffer
func (value TestIbcTransferWithTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestIbcTransferWithTransferCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field SourcePort: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourcePort, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field SourceChannel: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourceChannel, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[96:]); err != nil {
		return 0, err
	}

	// Field Sender: address
	if _, err := abi.EncodeAddress(value.Sender, buf[128:]); err != nil {
		return 0, err
	}

	// Field Receiver: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Receiver, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field TimeoutHeight: (uint64,uint64)
	if _, err := value.TimeoutHeight.EncodeTo(buf[192:]); err != nil {
		return 0, err
	}

	// Field TimeoutTimestamp: uint64
	if _, err := abi.EncodeUint64(value.TimeoutTimestamp, buf[256:]); err != nil {
		return 0, err
	}

	// Field Memo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[288+24:288+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Memo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Before: bool
	if _, err := abi.EncodeBool(value.Before, buf[320:]); err != nil {
		return 0, err
	}

	// Field After: bool
	if _, err := abi.EncodeBool(value.After, buf[352:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestIbcTransferWithTransferCall to ABI bytes
func (value TestIbcTransferWithTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestIbcTransferWithTransferCall from ABI bytes in the provided buffer
func (t *TestIbcTransferWithTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 384 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 384
	// Decode dynamic field SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourcePort")
		}
		t.SourcePort, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourceChannel")
		}
		t.SourceChannel, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Denom
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Denom")
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field Sender: address
	t.Sender, _, err = abi.DecodeAddress(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Receiver
	{
		offset := int(binary.BigEndian.Uint64(data[160+24 : 160+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Receiver")
		}
		t.Receiver, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field TimeoutHeight: (uint64,uint64)
	_, err = t.TimeoutHeight.Decode(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field TimeoutTimestamp: uint64
	t.TimeoutTimestamp, _, err = abi.DecodeUint64(data[256:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Memo
	{
		offset := int(binary.BigEndian.Uint64(data[288+24 : 288+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Memo")
		}
		t.Memo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Before: bool
	t.Before, _, err = abi.DecodeBool(data[320:])
	if err != nil {
		return 0, err
	}
	// Decode static field After: bool
	t.After, _, err = abi.DecodeBool(data[352:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestIbcTransferWithTransferCall) GetMethodName() string {
	return "testIbcTransferWithTransfer"
}

// GetMethodID returns the function name
func (t TestIbcTransferWithTransferCall) GetMethodID() uint32 {
	return TestIbcTransferWithTransferID
}

// GetMethodSelector returns the function name
func (t TestIbcTransferWithTransferCall) GetMethodSelector() [4]byte {
	return TestIbcTransferWithTransferSelector
}

// EncodeWithSelector encodes testIbcTransferWithTransfer arguments to ABI bytes including function selector
func (t TestIbcTransferWithTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestIbcTransferWithTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const TestIbcTransferWithTransferReturnStaticSize = 32

var _ abi.Tuple = (*TestIbcTransferWithTransferReturn)(nil)

// TestIbcTransferWithTransferReturn represents an ABI tuple
type TestIbcTransferWithTransferReturn struct {
	Field1 uint64
}

// EncodedSize returns the total encoded size of TestIbcTransferWithTransferReturn
func (t TestIbcTransferWithTransferReturn) EncodedSize() int {
	dynamicSize := 0

	return TestIbcTransferWithTransferReturnStaticSize + dynamicSize
}

// EncodeTo encodes TestIbcTransferWithTransferReturn to ABI bytes in the provided buffer
func (value TestIbcTransferWithTransferReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestIbcTransferWithTransferReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint64
	if _, err := abi.EncodeUint64(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestIbcTransferWithTransferReturn to ABI bytes
func (value TestIbcTransferWithTransferReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestIbcTransferWithTransferReturn from ABI bytes in the provided buffer
func (t *TestIbcTransferWithTransferReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint64
	t.Field1, _, err = abi.DecodeUint64(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*TestRevertIbcTransferCall)(nil)

const TestRevertIbcTransferCallStaticSize = 384

var _ abi.Tuple = (*TestRevertIbcTransferCall)(nil)

// TestRevertIbcTransferCall represents an ABI tuple
type TestRevertIbcTransferCall struct {
	SourcePort       string
	SourceChannel    string
	Denom            string
	Amount           *big.Int
	Sender           common.Address
	Receiver         string
	ReceiverAddr     common.Address
	TimeoutHeight    Height
	TimeoutTimestamp uint64
	Memo             string
	After            bool
}

// EncodedSize returns the total encoded size of TestRevertIbcTransferCall
func (t TestRevertIbcTransferCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.SourcePort)
	dynamicSize += abi.SizeString(t.SourceChannel)
	dynamicSize += abi.SizeString(t.Denom)
	dynamicSize += abi.SizeString(t.Receiver)
	dynamicSize += abi.SizeString(t.Memo)

	return TestRevertIbcTransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TestRevertIbcTransferCall to ABI bytes in the provided buffer
func (value TestRevertIbcTransferCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := TestRevertIbcTransferCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field SourcePort: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourcePort, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field SourceChannel: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.SourceChannel, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Denom: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Denom, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[96:]); err != nil {
		return 0, err
	}

	// Field Sender: address
	if _, err := abi.EncodeAddress(value.Sender, buf[128:]); err != nil {
		return 0, err
	}

	// Field Receiver: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Receiver, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field ReceiverAddr: address
	if _, err := abi.EncodeAddress(value.ReceiverAddr, buf[192:]); err != nil {
		return 0, err
	}

	// Field TimeoutHeight: (uint64,uint64)
	if _, err := value.TimeoutHeight.EncodeTo(buf[224:]); err != nil {
		return 0, err
	}

	// Field TimeoutTimestamp: uint64
	if _, err := abi.EncodeUint64(value.TimeoutTimestamp, buf[288:]); err != nil {
		return 0, err
	}

	// Field Memo: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[320+24:320+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Memo, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field After: bool
	if _, err := abi.EncodeBool(value.After, buf[352:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes TestRevertIbcTransferCall to ABI bytes
func (value TestRevertIbcTransferCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TestRevertIbcTransferCall from ABI bytes in the provided buffer
func (t *TestRevertIbcTransferCall) Decode(data []byte) (int, error) {
	if len(data) < 384 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 384
	// Decode dynamic field SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data[0+24 : 0+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourcePort")
		}
		t.SourcePort, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field SourceChannel")
		}
		t.SourceChannel, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode dynamic field Denom
	{
		offset := int(binary.BigEndian.Uint64(data[64+24 : 64+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Denom")
		}
		t.Denom, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[96:])
	if err != nil {
		return 0, err
	}
	// Decode static field Sender: address
	t.Sender, _, err = abi.DecodeAddress(data[128:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Receiver
	{
		offset := int(binary.BigEndian.Uint64(data[160+24 : 160+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Receiver")
		}
		t.Receiver, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field ReceiverAddr: address
	t.ReceiverAddr, _, err = abi.DecodeAddress(data[192:])
	if err != nil {
		return 0, err
	}
	// Decode static field TimeoutHeight: (uint64,uint64)
	_, err = t.TimeoutHeight.Decode(data[224:])
	if err != nil {
		return 0, err
	}
	// Decode static field TimeoutTimestamp: uint64
	t.TimeoutTimestamp, _, err = abi.DecodeUint64(data[288:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Memo
	{
		offset := int(binary.BigEndian.Uint64(data[320+24 : 320+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Memo")
		}
		t.Memo, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field After: bool
	t.After, _, err = abi.DecodeBool(data[352:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t TestRevertIbcTransferCall) GetMethodName() string {
	return "testRevertIbcTransfer"
}

// GetMethodID returns the function name
func (t TestRevertIbcTransferCall) GetMethodID() uint32 {
	return TestRevertIbcTransferID
}

// GetMethodSelector returns the function name
func (t TestRevertIbcTransferCall) GetMethodSelector() [4]byte {
	return TestRevertIbcTransferSelector
}

// EncodeWithSelector encodes testRevertIbcTransfer arguments to ABI bytes including function selector
func (t TestRevertIbcTransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TestRevertIbcTransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// TestRevertIbcTransferReturn represents the input arguments for testRevertIbcTransfer function
type TestRevertIbcTransferReturn struct {
	abi.EmptyTuple
}
