// Code generated by go-abi. DO NOT EDIT.

package flashloan

import (
	"encoding/binary"
	"errors"
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// delegateWithRevert(address,string,uint256)
	DelegateWithRevertSelector = [4]byte{0x8f, 0x51, 0x84, 0x30}
	// flashLoan(address,string)
	FlashLoanSelector = [4]byte{0xb8, 0x62, 0x19, 0x24}
	// flashLoanWithRevert(address,string)
	FlashLoanWithRevertSelector = [4]byte{0x9b, 0x4f, 0x21, 0xa9}
	// owner()
	OwnerSelector = [4]byte{0x8d, 0xa5, 0xcb, 0x5b}
)

// Big endian integer versions of function selectors
const (
	DelegateWithRevertID  = 2404484144
	FlashLoanID           = 3093436708
	FlashLoanWithRevertID = 2605654441
	OwnerID               = 2376452955
)

var _ abi.Method = (*DelegateWithRevertCall)(nil)

const DelegateWithRevertCallStaticSize = 96

var _ abi.Tuple = (*DelegateWithRevertCall)(nil)

// DelegateWithRevertCall represents an ABI tuple
type DelegateWithRevertCall struct {
	Delegator common.Address
	Validator string
	Amount    *big.Int
}

// EncodedSize returns the total encoded size of DelegateWithRevertCall
func (t DelegateWithRevertCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Validator)

	return DelegateWithRevertCallStaticSize + dynamicSize
}

// EncodeTo encodes DelegateWithRevertCall to ABI bytes in the provided buffer
func (value DelegateWithRevertCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := DelegateWithRevertCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Delegator: address
	if _, err := abi.EncodeAddress(value.Delegator, buf[0:]); err != nil {
		return 0, err
	}

	// Field Validator: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Validator, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	// Field Amount: uint256
	if _, err := abi.EncodeUint256(value.Amount, buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes DelegateWithRevertCall to ABI bytes
func (value DelegateWithRevertCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegateWithRevertCall from ABI bytes in the provided buffer
func (t *DelegateWithRevertCall) Decode(data []byte) (int, error) {
	if len(data) < 96 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 96
	// Decode static field Delegator: address
	t.Delegator, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Validator
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Validator")
		}
		t.Validator, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// Decode static field Amount: uint256
	t.Amount, _, err = abi.DecodeUint256(data[64:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t DelegateWithRevertCall) GetMethodName() string {
	return "delegateWithRevert"
}

// GetMethodID returns the function name
func (t DelegateWithRevertCall) GetMethodID() uint32 {
	return DelegateWithRevertID
}

// GetMethodSelector returns the function name
func (t DelegateWithRevertCall) GetMethodSelector() [4]byte {
	return DelegateWithRevertSelector
}

// EncodeWithSelector encodes delegateWithRevert arguments to ABI bytes including function selector
func (t DelegateWithRevertCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DelegateWithRevertSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// DelegateWithRevertReturn represents the input arguments for delegateWithRevert function
type DelegateWithRevertReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*FlashLoanCall)(nil)

const FlashLoanCallStaticSize = 64

var _ abi.Tuple = (*FlashLoanCall)(nil)

// FlashLoanCall represents an ABI tuple
type FlashLoanCall struct {
	Token     common.Address
	Validator string
}

// EncodedSize returns the total encoded size of FlashLoanCall
func (t FlashLoanCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Validator)

	return FlashLoanCallStaticSize + dynamicSize
}

// EncodeTo encodes FlashLoanCall to ABI bytes in the provided buffer
func (value FlashLoanCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := FlashLoanCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Token: address
	if _, err := abi.EncodeAddress(value.Token, buf[0:]); err != nil {
		return 0, err
	}

	// Field Validator: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Validator, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes FlashLoanCall to ABI bytes
func (value FlashLoanCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes FlashLoanCall from ABI bytes in the provided buffer
func (t *FlashLoanCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 64
	// Decode static field Token: address
	t.Token, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Validator
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Validator")
		}
		t.Validator, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t FlashLoanCall) GetMethodName() string {
	return "flashLoan"
}

// GetMethodID returns the function name
func (t FlashLoanCall) GetMethodID() uint32 {
	return FlashLoanID
}

// GetMethodSelector returns the function name
func (t FlashLoanCall) GetMethodSelector() [4]byte {
	return FlashLoanSelector
}

// EncodeWithSelector encodes flashLoan arguments to ABI bytes including function selector
func (t FlashLoanCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], FlashLoanSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const FlashLoanReturnStaticSize = 32

var _ abi.Tuple = (*FlashLoanReturn)(nil)

// FlashLoanReturn represents an ABI tuple
type FlashLoanReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of FlashLoanReturn
func (t FlashLoanReturn) EncodedSize() int {
	dynamicSize := 0

	return FlashLoanReturnStaticSize + dynamicSize
}

// EncodeTo encodes FlashLoanReturn to ABI bytes in the provided buffer
func (value FlashLoanReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := FlashLoanReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes FlashLoanReturn to ABI bytes
func (value FlashLoanReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes FlashLoanReturn from ABI bytes in the provided buffer
func (t *FlashLoanReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*FlashLoanWithRevertCall)(nil)

const FlashLoanWithRevertCallStaticSize = 64

var _ abi.Tuple = (*FlashLoanWithRevertCall)(nil)

// FlashLoanWithRevertCall represents an ABI tuple
type FlashLoanWithRevertCall struct {
	Token     common.Address
	Validator string
}

// EncodedSize returns the total encoded size of FlashLoanWithRevertCall
func (t FlashLoanWithRevertCall) EncodedSize() int {
	dynamicSize := 0
	dynamicSize += abi.SizeString(t.Validator)

	return FlashLoanWithRevertCallStaticSize + dynamicSize
}

// EncodeTo encodes FlashLoanWithRevertCall to ABI bytes in the provided buffer
func (value FlashLoanWithRevertCall) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := FlashLoanWithRevertCallStaticSize // Start dynamic data after static section
	var (
		err error
		n   int
	)
	// Field Token: address
	if _, err := abi.EncodeAddress(value.Token, buf[0:]); err != nil {
		return 0, err
	}

	// Field Validator: string
	// Encode offset pointer
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))
	// Encode dynamic data
	n, err = abi.EncodeString(value.Validator, buf[dynamicOffset:])
	if err != nil {
		return 0, err
	}
	dynamicOffset += n

	return dynamicOffset, nil
}

// Encode encodes FlashLoanWithRevertCall to ABI bytes
func (value FlashLoanWithRevertCall) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes FlashLoanWithRevertCall from ABI bytes in the provided buffer
func (t *FlashLoanWithRevertCall) Decode(data []byte) (int, error) {
	if len(data) < 64 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
		n   int
	)
	dynamicOffset := 64
	// Decode static field Token: address
	t.Token, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	// Decode dynamic field Validator
	{
		offset := int(binary.BigEndian.Uint64(data[32+24 : 32+32]))
		if offset != dynamicOffset {
			return 0, errors.New("invalid offset for dynamic field Validator")
		}
		t.Validator, n, err = abi.DecodeString(data[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	return dynamicOffset, nil
}

// GetMethodName returns the function name
func (t FlashLoanWithRevertCall) GetMethodName() string {
	return "flashLoanWithRevert"
}

// GetMethodID returns the function name
func (t FlashLoanWithRevertCall) GetMethodID() uint32 {
	return FlashLoanWithRevertID
}

// GetMethodSelector returns the function name
func (t FlashLoanWithRevertCall) GetMethodSelector() [4]byte {
	return FlashLoanWithRevertSelector
}

// EncodeWithSelector encodes flashLoanWithRevert arguments to ABI bytes including function selector
func (t FlashLoanWithRevertCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], FlashLoanWithRevertSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const FlashLoanWithRevertReturnStaticSize = 32

var _ abi.Tuple = (*FlashLoanWithRevertReturn)(nil)

// FlashLoanWithRevertReturn represents an ABI tuple
type FlashLoanWithRevertReturn struct {
	Field1 bool
}

// EncodedSize returns the total encoded size of FlashLoanWithRevertReturn
func (t FlashLoanWithRevertReturn) EncodedSize() int {
	dynamicSize := 0

	return FlashLoanWithRevertReturnStaticSize + dynamicSize
}

// EncodeTo encodes FlashLoanWithRevertReturn to ABI bytes in the provided buffer
func (value FlashLoanWithRevertReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := FlashLoanWithRevertReturnStaticSize // Start dynamic data after static section
	// Field Field1: bool
	if _, err := abi.EncodeBool(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes FlashLoanWithRevertReturn to ABI bytes
func (value FlashLoanWithRevertReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes FlashLoanWithRevertReturn from ABI bytes in the provided buffer
func (t *FlashLoanWithRevertReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: bool
	t.Field1, _, err = abi.DecodeBool(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*OwnerCall)(nil)

// OwnerCall represents the input arguments for owner function
type OwnerCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t OwnerCall) GetMethodName() string {
	return "owner"
}

// GetMethodID returns the function name
func (t OwnerCall) GetMethodID() uint32 {
	return OwnerID
}

// GetMethodSelector returns the function name
func (t OwnerCall) GetMethodSelector() [4]byte {
	return OwnerSelector
}

// EncodeWithSelector encodes owner arguments to ABI bytes including function selector
func (t OwnerCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], OwnerSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const OwnerReturnStaticSize = 32

var _ abi.Tuple = (*OwnerReturn)(nil)

// OwnerReturn represents an ABI tuple
type OwnerReturn struct {
	Field1 common.Address
}

// EncodedSize returns the total encoded size of OwnerReturn
func (t OwnerReturn) EncodedSize() int {
	dynamicSize := 0

	return OwnerReturnStaticSize + dynamicSize
}

// EncodeTo encodes OwnerReturn to ABI bytes in the provided buffer
func (value OwnerReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := OwnerReturnStaticSize // Start dynamic data after static section
	// Field Field1: address
	if _, err := abi.EncodeAddress(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes OwnerReturn to ABI bytes
func (value OwnerReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes OwnerReturn from ABI bytes in the provided buffer
func (t *OwnerReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: address
	t.Field1, _, err = abi.DecodeAddress(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}
