// Code generated by go-abi. DO NOT EDIT.

package bech32

import (
	"encoding/binary"
	"fmt"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// bech32ToHex(string)
	Bech32ToHexSelector = [4]byte{0xe6, 0xdf, 0x46, 0x1e}
	// hexToBech32(address,string)
	HexToBech32Selector = [4]byte{0xf9, 0x58, 0xa9, 0x8c}
)

// Big endian integer versions of function selectors
const (
	Bech32ToHexID = 3873392158
	HexToBech32ID = 4183337356
)

const Bech32ToHexCallStaticSize = 32

// Bech32ToHexCall represents an ABI tuple
type Bech32ToHexCall struct {
	Bech32Address string
}

// EncodedSize returns the total encoded size of Bech32ToHexCall
func (t Bech32ToHexCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Bech32Address)) // length + padded string data

	return Bech32ToHexCallStaticSize + dynamicSize
}

// EncodeTo encodes Bech32ToHexCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Bech32ToHexCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := Bech32ToHexCallStaticSize // Start dynamic data after static section

	// Bech32Address (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Bech32Address (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Bech32Address)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Bech32Address))
	dynamicOffset += abi.Pad32(len(t.Bech32Address))

	return dynamicOffset, nil
}

// Encode encodes Bech32ToHexCall to ABI bytes
func (t Bech32ToHexCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Bech32ToHexCall from ABI bytes in the provided buffer
func (t *Bech32ToHexCall) Decode(data0 []byte) error {
	if len(data0) < Bech32ToHexCallStaticSize {
		return fmt.Errorf("insufficient data for Bech32ToHexCall")
	}

	// Bech32Address
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Bech32Address (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Bech32Address = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes bech32ToHex arguments to ABI bytes including function selector
func (t Bech32ToHexCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], Bech32ToHexSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const Bech32ToHexReturnStaticSize = 32

// Bech32ToHexReturn represents an ABI tuple
type Bech32ToHexReturn struct {
	Addr common.Address
}

// EncodedSize returns the total encoded size of Bech32ToHexReturn
func (t Bech32ToHexReturn) EncodedSize() int {
	dynamicSize := 0

	return Bech32ToHexReturnStaticSize + dynamicSize
}

// EncodeTo encodes Bech32ToHexReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Bech32ToHexReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := Bech32ToHexReturnStaticSize // Start dynamic data after static section

	// Addr (static)
	copy(buf[0+12:0+32], t.Addr[:])

	return dynamicOffset, nil
}

// Encode encodes Bech32ToHexReturn to ABI bytes
func (t Bech32ToHexReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Bech32ToHexReturn from ABI bytes in the provided buffer
func (t *Bech32ToHexReturn) Decode(data0 []byte) error {
	if len(data0) < Bech32ToHexReturnStaticSize {
		return fmt.Errorf("insufficient data for Bech32ToHexReturn")
	}

	// t.Addr (static)
	copy(t.Addr[:], data0[0+12:0+32])

	return nil
}

const HexToBech32CallStaticSize = 64

// HexToBech32Call represents an ABI tuple
type HexToBech32Call struct {
	Addr   common.Address
	Prefix string
}

// EncodedSize returns the total encoded size of HexToBech32Call
func (t HexToBech32Call) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Prefix)) // length + padded string data

	return HexToBech32CallStaticSize + dynamicSize
}

// EncodeTo encodes HexToBech32Call to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t HexToBech32Call) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := HexToBech32CallStaticSize // Start dynamic data after static section

	// Addr (static)
	copy(buf[0+12:0+32], t.Addr[:])

	// Prefix (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// Prefix (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Prefix)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Prefix))
	dynamicOffset += abi.Pad32(len(t.Prefix))

	return dynamicOffset, nil
}

// Encode encodes HexToBech32Call to ABI bytes
func (t HexToBech32Call) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes HexToBech32Call from ABI bytes in the provided buffer
func (t *HexToBech32Call) Decode(data0 []byte) error {
	if len(data0) < HexToBech32CallStaticSize {
		return fmt.Errorf("insufficient data for HexToBech32Call")
	}

	// t.Addr (static)
	copy(t.Addr[:], data0[0+12:0+32])
	// Prefix
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.Prefix (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Prefix = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes hexToBech32 arguments to ABI bytes including function selector
func (t HexToBech32Call) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], HexToBech32Selector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const HexToBech32ReturnStaticSize = 32

// HexToBech32Return represents an ABI tuple
type HexToBech32Return struct {
	Bech32Address string
}

// EncodedSize returns the total encoded size of HexToBech32Return
func (t HexToBech32Return) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Bech32Address)) // length + padded string data

	return HexToBech32ReturnStaticSize + dynamicSize
}

// EncodeTo encodes HexToBech32Return to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t HexToBech32Return) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := HexToBech32ReturnStaticSize // Start dynamic data after static section

	// Bech32Address (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Bech32Address (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Bech32Address)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Bech32Address))
	dynamicOffset += abi.Pad32(len(t.Bech32Address))

	return dynamicOffset, nil
}

// Encode encodes HexToBech32Return to ABI bytes
func (t HexToBech32Return) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes HexToBech32Return from ABI bytes in the provided buffer
func (t *HexToBech32Return) Decode(data0 []byte) error {
	if len(data0) < HexToBech32ReturnStaticSize {
		return fmt.Errorf("insufficient data for HexToBech32Return")
	}

	// Bech32Address
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Bech32Address (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Bech32Address = string(data0[offset : offset+length])
	}

	return nil
}
