// Code generated by go-abi. DO NOT EDIT.

package distribution

import (
	"encoding/binary"
	"fmt"

	cmn "github.com/cosmos/evm/precompiles/common"
	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// claimRewards(address,uint32)
	ClaimRewardsSelector = [4]byte{0x2e, 0xfe, 0x8a, 0x5f}
	// communityPool()
	CommunityPoolSelector = [4]byte{0x14, 0xd1, 0x40, 0xb0}
	// delegationRewards(address,string)
	DelegationRewardsSelector = [4]byte{0x9a, 0xd5, 0x63, 0xb4}
	// delegationTotalRewards(address)
	DelegationTotalRewardsSelector = [4]byte{0x54, 0xbe, 0x1a, 0x28}
	// delegatorValidators(address)
	DelegatorValidatorsSelector = [4]byte{0xa6, 0x6c, 0xb6, 0x05}
	// delegatorWithdrawAddress(address)
	DelegatorWithdrawAddressSelector = [4]byte{0x54, 0x31, 0xf4, 0x50}
	// depositValidatorRewardsPool(address,string,(string,uint256)[])
	DepositValidatorRewardsPoolSelector = [4]byte{0x2e, 0xb1, 0xdf, 0x52}
	// fundCommunityPool(address,(string,uint256)[])
	FundCommunityPoolSelector = [4]byte{0x2d, 0x2b, 0x07, 0x9c}
	// setWithdrawAddress(address,string)
	SetWithdrawAddressSelector = [4]byte{0x5a, 0x9d, 0x9a, 0x96}
	// validatorCommission(string)
	ValidatorCommissionSelector = [4]byte{0x3d, 0xd4, 0x0f, 0x78}
	// validatorDistributionInfo(string)
	ValidatorDistributionInfoSelector = [4]byte{0x54, 0x21, 0x2a, 0x89}
	// validatorOutstandingRewards(string)
	ValidatorOutstandingRewardsSelector = [4]byte{0x85, 0xb2, 0xd2, 0xda}
	// validatorSlashes(string,uint64,uint64,(bytes,uint64,uint64,bool,bool))
	ValidatorSlashesSelector = [4]byte{0x8f, 0x24, 0x73, 0xce}
	// withdrawDelegatorRewards(address,string)
	WithdrawDelegatorRewardsSelector = [4]byte{0xb4, 0x6a, 0x8d, 0x61}
	// withdrawValidatorCommission(string)
	WithdrawValidatorCommissionSelector = [4]byte{0x3c, 0xe4, 0xe3, 0xbe}
)

// Big endian integer versions of function selectors
const (
	ClaimRewardsID                = 788433503
	CommunityPoolID               = 349257904
	DelegationRewardsID           = 2597675956
	DelegationTotalRewardsID      = 1421744680
	DelegatorValidatorsID         = 2792142341
	DelegatorWithdrawAddressID    = 1412559952
	DepositValidatorRewardsPoolID = 783408978
	FundCommunityPoolID           = 757794716
	SetWithdrawAddressID          = 1520278166
	ValidatorCommissionID         = 1037307768
	ValidatorDistributionInfoID   = 1411459721
	ValidatorOutstandingRewardsID = 2243089114
	ValidatorSlashesID            = 2401530830
	WithdrawDelegatorRewardsID    = 3026881889
	WithdrawValidatorCommissionID = 1021633470
)

const DelegationDelegatorRewardStaticSize = 64

// DelegationDelegatorReward represents an ABI tuple
type DelegationDelegatorReward struct {
	ValidatorAddress string
	Reward           []cmn.DecCoin
}

// EncodedSize returns the total encoded size of DelegationDelegatorReward
func (t DelegationDelegatorReward) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data
	dynamicSize += 32 + 32*len(t.Reward)                   // length + offset pointers for dynamic elements
	for _, elem := range t.Reward {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return DelegationDelegatorRewardStaticSize + dynamicSize
}

// EncodeTo encodes DelegationDelegatorReward to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegationDelegatorReward) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegationDelegatorRewardStaticSize // Start dynamic data after static section

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	// Reward (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// Reward (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Reward)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Reward) * 32 // start after static region

			var offset int
			for _, item := range t.Reward {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes DelegationDelegatorReward to ABI bytes
func (t DelegationDelegatorReward) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationDelegatorReward from ABI bytes in the provided buffer
func (t *DelegationDelegatorReward) Decode(data0 []byte) error {
	if len(data0) < DelegationDelegatorRewardStaticSize {
		return fmt.Errorf("insufficient data for DelegationDelegatorReward")
	}

	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}
	// Reward
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.Reward (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Reward = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Reward[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Reward[i0]")
			}
			if err := t.Reward[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const PageRequestStaticSize = 160

// PageRequest represents an ABI tuple
type PageRequest struct {
	Key        []byte
	Offset     uint64
	Limit      uint64
	CountTotal bool
	Reverse    bool
}

// EncodedSize returns the total encoded size of PageRequest
func (t PageRequest) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Key)) // length + padded bytes data

	return PageRequestStaticSize + dynamicSize
}

// EncodeTo encodes PageRequest to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t PageRequest) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := PageRequestStaticSize // Start dynamic data after static section

	// Key (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Key (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Key)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], t.Key)
	dynamicOffset += abi.Pad32(len(t.Key))

	// Offset (static)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(t.Offset))
	// Limit (static)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(t.Limit))
	// CountTotal (static)

	if t.CountTotal {
		buf[96+31] = 1
	}

	// Reverse (static)

	if t.Reverse {
		buf[128+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes PageRequest to ABI bytes
func (t PageRequest) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PageRequest from ABI bytes in the provided buffer
func (t *PageRequest) Decode(data0 []byte) error {
	if len(data0) < PageRequestStaticSize {
		return fmt.Errorf("insufficient data for PageRequest")
	}

	// Key
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Key (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// bytes data
		t.Key = data0[offset : offset+length]
	}
	// t.Offset (static)
	t.Offset = uint64(binary.BigEndian.Uint64(data0[32+24 : 32+32]))
	// t.Limit (static)
	t.Limit = uint64(binary.BigEndian.Uint64(data0[64+24 : 64+32]))
	// t.CountTotal (static)
	t.CountTotal = data0[96+31] == 1
	// t.Reverse (static)
	t.Reverse = data0[128+31] == 1

	return nil
}

const PageResponseStaticSize = 64

// PageResponse represents an ABI tuple
type PageResponse struct {
	NextKey []byte
	Total   uint64
}

// EncodedSize returns the total encoded size of PageResponse
func (t PageResponse) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.NextKey)) // length + padded bytes data

	return PageResponseStaticSize + dynamicSize
}

// EncodeTo encodes PageResponse to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t PageResponse) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := PageResponseStaticSize // Start dynamic data after static section

	// NextKey (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// NextKey (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.NextKey)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], t.NextKey)
	dynamicOffset += abi.Pad32(len(t.NextKey))

	// Total (static)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(t.Total))

	return dynamicOffset, nil
}

// Encode encodes PageResponse to ABI bytes
func (t PageResponse) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PageResponse from ABI bytes in the provided buffer
func (t *PageResponse) Decode(data0 []byte) error {
	if len(data0) < PageResponseStaticSize {
		return fmt.Errorf("insufficient data for PageResponse")
	}

	// NextKey
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.NextKey (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// bytes data
		t.NextKey = data0[offset : offset+length]
	}
	// t.Total (static)
	t.Total = uint64(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

	return nil
}

const ValidatorDistributionInfoStaticSize = 96

// ValidatorDistributionInfo represents an ABI tuple
type ValidatorDistributionInfo struct {
	OperatorAddress string
	SelfBondRewards []cmn.DecCoin
	Commission      []cmn.DecCoin
}

// EncodedSize returns the total encoded size of ValidatorDistributionInfo
func (t ValidatorDistributionInfo) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.OperatorAddress)) // length + padded string data
	dynamicSize += 32 + 32*len(t.SelfBondRewards)         // length + offset pointers for dynamic elements
	for _, elem := range t.SelfBondRewards {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}
	dynamicSize += 32 + 32*len(t.Commission) // length + offset pointers for dynamic elements
	for _, elem := range t.Commission {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return ValidatorDistributionInfoStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorDistributionInfo to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorDistributionInfo) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorDistributionInfoStaticSize // Start dynamic data after static section

	// OperatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// OperatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.OperatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.OperatorAddress))
	dynamicOffset += abi.Pad32(len(t.OperatorAddress))

	// SelfBondRewards (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// SelfBondRewards (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.SelfBondRewards)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.SelfBondRewards) * 32 // start after static region

			var offset int
			for _, item := range t.SelfBondRewards {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	// Commission (offset)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))

	// Commission (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Commission)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Commission) * 32 // start after static region

			var offset int
			for _, item := range t.Commission {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorDistributionInfo to ABI bytes
func (t ValidatorDistributionInfo) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorDistributionInfo from ABI bytes in the provided buffer
func (t *ValidatorDistributionInfo) Decode(data0 []byte) error {
	if len(data0) < ValidatorDistributionInfoStaticSize {
		return fmt.Errorf("insufficient data for ValidatorDistributionInfo")
	}

	// OperatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.OperatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.OperatorAddress = string(data0[offset : offset+length])
	}
	// SelfBondRewards
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.SelfBondRewards (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.SelfBondRewards = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.SelfBondRewards[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.SelfBondRewards[i0]")
			}
			if err := t.SelfBondRewards[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}
	// Commission
	{
		offset := int(binary.BigEndian.Uint64(data0[64+24 : 64+32]))

		// t.Commission (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Commission = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Commission[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Commission[i0]")
			}
			if err := t.Commission[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const ValidatorSlashEventStaticSize = 96

// ValidatorSlashEvent represents an ABI tuple
type ValidatorSlashEvent struct {
	ValidatorPeriod uint64
	Fraction        cmn.Dec
}

// EncodedSize returns the total encoded size of ValidatorSlashEvent
func (t ValidatorSlashEvent) EncodedSize() int {
	dynamicSize := 0

	return ValidatorSlashEventStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorSlashEvent to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorSlashEvent) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorSlashEventStaticSize // Start dynamic data after static section

	// ValidatorPeriod (static)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(t.ValidatorPeriod))
	// Fraction (static)

	// Encode nested tuple t.Fraction
	if _, err := t.Fraction.EncodeTo(buf[32:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorSlashEvent to ABI bytes
func (t ValidatorSlashEvent) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorSlashEvent from ABI bytes in the provided buffer
func (t *ValidatorSlashEvent) Decode(data0 []byte) error {
	if len(data0) < ValidatorSlashEventStaticSize {
		return fmt.Errorf("insufficient data for ValidatorSlashEvent")
	}

	// t.ValidatorPeriod (static)
	t.ValidatorPeriod = uint64(binary.BigEndian.Uint64(data0[0+24 : 0+32]))
	// t.Fraction (static)
	if err := t.Fraction.Decode(data0[32:96]); err != nil {
		return err
	}

	return nil
}

const ClaimRewardsCallStaticSize = 64

// ClaimRewardsCall represents an ABI tuple
type ClaimRewardsCall struct {
	DelegatorAddress common.Address
	MaxRetrieve      uint32
}

// EncodedSize returns the total encoded size of ClaimRewardsCall
func (t ClaimRewardsCall) EncodedSize() int {
	dynamicSize := 0

	return ClaimRewardsCallStaticSize + dynamicSize
}

// EncodeTo encodes ClaimRewardsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ClaimRewardsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ClaimRewardsCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])
	// MaxRetrieve (static)
	binary.BigEndian.PutUint32(buf[32+28:32+32], uint32(t.MaxRetrieve))

	return dynamicOffset, nil
}

// Encode encodes ClaimRewardsCall to ABI bytes
func (t ClaimRewardsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ClaimRewardsCall from ABI bytes in the provided buffer
func (t *ClaimRewardsCall) Decode(data0 []byte) error {
	if len(data0) < ClaimRewardsCallStaticSize {
		return fmt.Errorf("insufficient data for ClaimRewardsCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])
	// t.MaxRetrieve (static)
	t.MaxRetrieve = uint32(binary.BigEndian.Uint32(data0[32+28 : 32+32]))

	return nil
}

// EncodeWithSelector encodes claimRewards arguments to ABI bytes including function selector
func (t ClaimRewardsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ClaimRewardsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const ClaimRewardsReturnStaticSize = 32

// ClaimRewardsReturn represents an ABI tuple
type ClaimRewardsReturn struct {
	Success bool
}

// EncodedSize returns the total encoded size of ClaimRewardsReturn
func (t ClaimRewardsReturn) EncodedSize() int {
	dynamicSize := 0

	return ClaimRewardsReturnStaticSize + dynamicSize
}

// EncodeTo encodes ClaimRewardsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ClaimRewardsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ClaimRewardsReturnStaticSize // Start dynamic data after static section

	// Success (static)

	if t.Success {
		buf[0+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes ClaimRewardsReturn to ABI bytes
func (t ClaimRewardsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ClaimRewardsReturn from ABI bytes in the provided buffer
func (t *ClaimRewardsReturn) Decode(data0 []byte) error {
	if len(data0) < ClaimRewardsReturnStaticSize {
		return fmt.Errorf("insufficient data for ClaimRewardsReturn")
	}

	// t.Success (static)
	t.Success = data0[0+31] == 1

	return nil
}

const CommunityPoolReturnStaticSize = 32

// CommunityPoolReturn represents an ABI tuple
type CommunityPoolReturn struct {
	Coins []cmn.DecCoin
}

// EncodedSize returns the total encoded size of CommunityPoolReturn
func (t CommunityPoolReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Coins) // length + offset pointers for dynamic elements
	for _, elem := range t.Coins {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return CommunityPoolReturnStaticSize + dynamicSize
}

// EncodeTo encodes CommunityPoolReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t CommunityPoolReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := CommunityPoolReturnStaticSize // Start dynamic data after static section

	// Coins (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Coins (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Coins)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Coins) * 32 // start after static region

			var offset int
			for _, item := range t.Coins {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes CommunityPoolReturn to ABI bytes
func (t CommunityPoolReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes CommunityPoolReturn from ABI bytes in the provided buffer
func (t *CommunityPoolReturn) Decode(data0 []byte) error {
	if len(data0) < CommunityPoolReturnStaticSize {
		return fmt.Errorf("insufficient data for CommunityPoolReturn")
	}

	// Coins
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Coins (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Coins = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Coins[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Coins[i0]")
			}
			if err := t.Coins[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const DelegationRewardsCallStaticSize = 64

// DelegationRewardsCall represents an ABI tuple
type DelegationRewardsCall struct {
	DelegatorAddress common.Address
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of DelegationRewardsCall
func (t DelegationRewardsCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data

	return DelegationRewardsCallStaticSize + dynamicSize
}

// EncodeTo encodes DelegationRewardsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegationRewardsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegationRewardsCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	return dynamicOffset, nil
}

// Encode encodes DelegationRewardsCall to ABI bytes
func (t DelegationRewardsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationRewardsCall from ABI bytes in the provided buffer
func (t *DelegationRewardsCall) Decode(data0 []byte) error {
	if len(data0) < DelegationRewardsCallStaticSize {
		return fmt.Errorf("insufficient data for DelegationRewardsCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])
	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes delegationRewards arguments to ABI bytes including function selector
func (t DelegationRewardsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DelegationRewardsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DelegationRewardsReturnStaticSize = 32

// DelegationRewardsReturn represents an ABI tuple
type DelegationRewardsReturn struct {
	Rewards []cmn.DecCoin
}

// EncodedSize returns the total encoded size of DelegationRewardsReturn
func (t DelegationRewardsReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Rewards) // length + offset pointers for dynamic elements
	for _, elem := range t.Rewards {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return DelegationRewardsReturnStaticSize + dynamicSize
}

// EncodeTo encodes DelegationRewardsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegationRewardsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegationRewardsReturnStaticSize // Start dynamic data after static section

	// Rewards (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Rewards (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Rewards)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Rewards) * 32 // start after static region

			var offset int
			for _, item := range t.Rewards {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes DelegationRewardsReturn to ABI bytes
func (t DelegationRewardsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationRewardsReturn from ABI bytes in the provided buffer
func (t *DelegationRewardsReturn) Decode(data0 []byte) error {
	if len(data0) < DelegationRewardsReturnStaticSize {
		return fmt.Errorf("insufficient data for DelegationRewardsReturn")
	}

	// Rewards
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Rewards (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Rewards = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Rewards[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Rewards[i0]")
			}
			if err := t.Rewards[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const DelegationTotalRewardsCallStaticSize = 32

// DelegationTotalRewardsCall represents an ABI tuple
type DelegationTotalRewardsCall struct {
	DelegatorAddress common.Address
}

// EncodedSize returns the total encoded size of DelegationTotalRewardsCall
func (t DelegationTotalRewardsCall) EncodedSize() int {
	dynamicSize := 0

	return DelegationTotalRewardsCallStaticSize + dynamicSize
}

// EncodeTo encodes DelegationTotalRewardsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegationTotalRewardsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegationTotalRewardsCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])

	return dynamicOffset, nil
}

// Encode encodes DelegationTotalRewardsCall to ABI bytes
func (t DelegationTotalRewardsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationTotalRewardsCall from ABI bytes in the provided buffer
func (t *DelegationTotalRewardsCall) Decode(data0 []byte) error {
	if len(data0) < DelegationTotalRewardsCallStaticSize {
		return fmt.Errorf("insufficient data for DelegationTotalRewardsCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes delegationTotalRewards arguments to ABI bytes including function selector
func (t DelegationTotalRewardsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DelegationTotalRewardsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DelegationTotalRewardsReturnStaticSize = 64

// DelegationTotalRewardsReturn represents an ABI tuple
type DelegationTotalRewardsReturn struct {
	Rewards []DelegationDelegatorReward
	Total   []cmn.DecCoin
}

// EncodedSize returns the total encoded size of DelegationTotalRewardsReturn
func (t DelegationTotalRewardsReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Rewards) // length + offset pointers for dynamic elements
	for _, elem := range t.Rewards {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}
	dynamicSize += 32 + 32*len(t.Total) // length + offset pointers for dynamic elements
	for _, elem := range t.Total {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return DelegationTotalRewardsReturnStaticSize + dynamicSize
}

// EncodeTo encodes DelegationTotalRewardsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegationTotalRewardsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegationTotalRewardsReturnStaticSize // Start dynamic data after static section

	// Rewards (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Rewards (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Rewards)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Rewards) * 32 // start after static region

			var offset int
			for _, item := range t.Rewards {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	// Total (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// Total (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Total)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Total) * 32 // start after static region

			var offset int
			for _, item := range t.Total {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes DelegationTotalRewardsReturn to ABI bytes
func (t DelegationTotalRewardsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegationTotalRewardsReturn from ABI bytes in the provided buffer
func (t *DelegationTotalRewardsReturn) Decode(data0 []byte) error {
	if len(data0) < DelegationTotalRewardsReturnStaticSize {
		return fmt.Errorf("insufficient data for DelegationTotalRewardsReturn")
	}

	// Rewards
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Rewards (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Rewards = make([]DelegationDelegatorReward, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Rewards[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Rewards[i0]")
			}
			if err := t.Rewards[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}
	// Total
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.Total (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Total = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Total[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Total[i0]")
			}
			if err := t.Total[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const DelegatorValidatorsCallStaticSize = 32

// DelegatorValidatorsCall represents an ABI tuple
type DelegatorValidatorsCall struct {
	DelegatorAddress common.Address
}

// EncodedSize returns the total encoded size of DelegatorValidatorsCall
func (t DelegatorValidatorsCall) EncodedSize() int {
	dynamicSize := 0

	return DelegatorValidatorsCallStaticSize + dynamicSize
}

// EncodeTo encodes DelegatorValidatorsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegatorValidatorsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegatorValidatorsCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])

	return dynamicOffset, nil
}

// Encode encodes DelegatorValidatorsCall to ABI bytes
func (t DelegatorValidatorsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegatorValidatorsCall from ABI bytes in the provided buffer
func (t *DelegatorValidatorsCall) Decode(data0 []byte) error {
	if len(data0) < DelegatorValidatorsCallStaticSize {
		return fmt.Errorf("insufficient data for DelegatorValidatorsCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes delegatorValidators arguments to ABI bytes including function selector
func (t DelegatorValidatorsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DelegatorValidatorsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DelegatorValidatorsReturnStaticSize = 32

// DelegatorValidatorsReturn represents an ABI tuple
type DelegatorValidatorsReturn struct {
	Validators []string
}

// EncodedSize returns the total encoded size of DelegatorValidatorsReturn
func (t DelegatorValidatorsReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Validators) // length + offset pointers for dynamic elements
	for _, elem := range t.Validators {
		dynamicSize += 32 + abi.Pad32(len(elem)) // length + padded string data
	}

	return DelegatorValidatorsReturnStaticSize + dynamicSize
}

// EncodeTo encodes DelegatorValidatorsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegatorValidatorsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegatorValidatorsReturnStaticSize // Start dynamic data after static section

	// Validators (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Validators (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Validators)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Validators) * 32 // start after static region

			var offset int
			for _, item := range t.Validators {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				// length
				binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(item)))
				dynamicOffset += 32

				// data
				copy(buf[dynamicOffset:], []byte(item))
				dynamicOffset += abi.Pad32(len(item))

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes DelegatorValidatorsReturn to ABI bytes
func (t DelegatorValidatorsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegatorValidatorsReturn from ABI bytes in the provided buffer
func (t *DelegatorValidatorsReturn) Decode(data0 []byte) error {
	if len(data0) < DelegatorValidatorsReturnStaticSize {
		return fmt.Errorf("insufficient data for DelegatorValidatorsReturn")
	}

	// Validators
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Validators (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Validators = make([]string, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Validators[i0] (dynamic)
			if offset+32 > len(data1) {
				return fmt.Errorf("insufficient data for length prefix")
			}
			length := int(binary.BigEndian.Uint64(data1[offset+24 : offset+32]))
			offset += 32
			// string data
			t.Validators[i0] = string(data1[offset : offset+length])
		}
	}

	return nil
}

const DelegatorWithdrawAddressCallStaticSize = 32

// DelegatorWithdrawAddressCall represents an ABI tuple
type DelegatorWithdrawAddressCall struct {
	DelegatorAddress common.Address
}

// EncodedSize returns the total encoded size of DelegatorWithdrawAddressCall
func (t DelegatorWithdrawAddressCall) EncodedSize() int {
	dynamicSize := 0

	return DelegatorWithdrawAddressCallStaticSize + dynamicSize
}

// EncodeTo encodes DelegatorWithdrawAddressCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegatorWithdrawAddressCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegatorWithdrawAddressCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])

	return dynamicOffset, nil
}

// Encode encodes DelegatorWithdrawAddressCall to ABI bytes
func (t DelegatorWithdrawAddressCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegatorWithdrawAddressCall from ABI bytes in the provided buffer
func (t *DelegatorWithdrawAddressCall) Decode(data0 []byte) error {
	if len(data0) < DelegatorWithdrawAddressCallStaticSize {
		return fmt.Errorf("insufficient data for DelegatorWithdrawAddressCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes delegatorWithdrawAddress arguments to ABI bytes including function selector
func (t DelegatorWithdrawAddressCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DelegatorWithdrawAddressSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DelegatorWithdrawAddressReturnStaticSize = 32

// DelegatorWithdrawAddressReturn represents an ABI tuple
type DelegatorWithdrawAddressReturn struct {
	WithdrawAddress string
}

// EncodedSize returns the total encoded size of DelegatorWithdrawAddressReturn
func (t DelegatorWithdrawAddressReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.WithdrawAddress)) // length + padded string data

	return DelegatorWithdrawAddressReturnStaticSize + dynamicSize
}

// EncodeTo encodes DelegatorWithdrawAddressReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DelegatorWithdrawAddressReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DelegatorWithdrawAddressReturnStaticSize // Start dynamic data after static section

	// WithdrawAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// WithdrawAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.WithdrawAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.WithdrawAddress))
	dynamicOffset += abi.Pad32(len(t.WithdrawAddress))

	return dynamicOffset, nil
}

// Encode encodes DelegatorWithdrawAddressReturn to ABI bytes
func (t DelegatorWithdrawAddressReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DelegatorWithdrawAddressReturn from ABI bytes in the provided buffer
func (t *DelegatorWithdrawAddressReturn) Decode(data0 []byte) error {
	if len(data0) < DelegatorWithdrawAddressReturnStaticSize {
		return fmt.Errorf("insufficient data for DelegatorWithdrawAddressReturn")
	}

	// WithdrawAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.WithdrawAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.WithdrawAddress = string(data0[offset : offset+length])
	}

	return nil
}

const DepositValidatorRewardsPoolCallStaticSize = 96

// DepositValidatorRewardsPoolCall represents an ABI tuple
type DepositValidatorRewardsPoolCall struct {
	Depositor        common.Address
	ValidatorAddress string
	Amount           []cmn.Coin
}

// EncodedSize returns the total encoded size of DepositValidatorRewardsPoolCall
func (t DepositValidatorRewardsPoolCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data
	dynamicSize += 32 + 32*len(t.Amount)                   // length + offset pointers for dynamic elements
	for _, elem := range t.Amount {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return DepositValidatorRewardsPoolCallStaticSize + dynamicSize
}

// EncodeTo encodes DepositValidatorRewardsPoolCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DepositValidatorRewardsPoolCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DepositValidatorRewardsPoolCallStaticSize // Start dynamic data after static section

	// Depositor (static)
	copy(buf[0+12:0+32], t.Depositor[:])

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	// Amount (offset)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))

	// Amount (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Amount)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Amount) * 32 // start after static region

			var offset int
			for _, item := range t.Amount {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes DepositValidatorRewardsPoolCall to ABI bytes
func (t DepositValidatorRewardsPoolCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DepositValidatorRewardsPoolCall from ABI bytes in the provided buffer
func (t *DepositValidatorRewardsPoolCall) Decode(data0 []byte) error {
	if len(data0) < DepositValidatorRewardsPoolCallStaticSize {
		return fmt.Errorf("insufficient data for DepositValidatorRewardsPoolCall")
	}

	// t.Depositor (static)
	copy(t.Depositor[:], data0[0+12:0+32])
	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}
	// Amount
	{
		offset := int(binary.BigEndian.Uint64(data0[64+24 : 64+32]))

		// t.Amount (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Amount = make([]cmn.Coin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Amount[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Amount[i0]")
			}
			if err := t.Amount[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

// EncodeWithSelector encodes depositValidatorRewardsPool arguments to ABI bytes including function selector
func (t DepositValidatorRewardsPoolCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DepositValidatorRewardsPoolSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DepositValidatorRewardsPoolReturnStaticSize = 32

// DepositValidatorRewardsPoolReturn represents an ABI tuple
type DepositValidatorRewardsPoolReturn struct {
	Success bool
}

// EncodedSize returns the total encoded size of DepositValidatorRewardsPoolReturn
func (t DepositValidatorRewardsPoolReturn) EncodedSize() int {
	dynamicSize := 0

	return DepositValidatorRewardsPoolReturnStaticSize + dynamicSize
}

// EncodeTo encodes DepositValidatorRewardsPoolReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DepositValidatorRewardsPoolReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DepositValidatorRewardsPoolReturnStaticSize // Start dynamic data after static section

	// Success (static)

	if t.Success {
		buf[0+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes DepositValidatorRewardsPoolReturn to ABI bytes
func (t DepositValidatorRewardsPoolReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DepositValidatorRewardsPoolReturn from ABI bytes in the provided buffer
func (t *DepositValidatorRewardsPoolReturn) Decode(data0 []byte) error {
	if len(data0) < DepositValidatorRewardsPoolReturnStaticSize {
		return fmt.Errorf("insufficient data for DepositValidatorRewardsPoolReturn")
	}

	// t.Success (static)
	t.Success = data0[0+31] == 1

	return nil
}

const FundCommunityPoolCallStaticSize = 64

// FundCommunityPoolCall represents an ABI tuple
type FundCommunityPoolCall struct {
	Depositor common.Address
	Amount    []cmn.Coin
}

// EncodedSize returns the total encoded size of FundCommunityPoolCall
func (t FundCommunityPoolCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Amount) // length + offset pointers for dynamic elements
	for _, elem := range t.Amount {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return FundCommunityPoolCallStaticSize + dynamicSize
}

// EncodeTo encodes FundCommunityPoolCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t FundCommunityPoolCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := FundCommunityPoolCallStaticSize // Start dynamic data after static section

	// Depositor (static)
	copy(buf[0+12:0+32], t.Depositor[:])

	// Amount (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// Amount (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Amount)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Amount) * 32 // start after static region

			var offset int
			for _, item := range t.Amount {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes FundCommunityPoolCall to ABI bytes
func (t FundCommunityPoolCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes FundCommunityPoolCall from ABI bytes in the provided buffer
func (t *FundCommunityPoolCall) Decode(data0 []byte) error {
	if len(data0) < FundCommunityPoolCallStaticSize {
		return fmt.Errorf("insufficient data for FundCommunityPoolCall")
	}

	// t.Depositor (static)
	copy(t.Depositor[:], data0[0+12:0+32])
	// Amount
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.Amount (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Amount = make([]cmn.Coin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Amount[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Amount[i0]")
			}
			if err := t.Amount[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

// EncodeWithSelector encodes fundCommunityPool arguments to ABI bytes including function selector
func (t FundCommunityPoolCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], FundCommunityPoolSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const FundCommunityPoolReturnStaticSize = 32

// FundCommunityPoolReturn represents an ABI tuple
type FundCommunityPoolReturn struct {
	Success bool
}

// EncodedSize returns the total encoded size of FundCommunityPoolReturn
func (t FundCommunityPoolReturn) EncodedSize() int {
	dynamicSize := 0

	return FundCommunityPoolReturnStaticSize + dynamicSize
}

// EncodeTo encodes FundCommunityPoolReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t FundCommunityPoolReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := FundCommunityPoolReturnStaticSize // Start dynamic data after static section

	// Success (static)

	if t.Success {
		buf[0+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes FundCommunityPoolReturn to ABI bytes
func (t FundCommunityPoolReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes FundCommunityPoolReturn from ABI bytes in the provided buffer
func (t *FundCommunityPoolReturn) Decode(data0 []byte) error {
	if len(data0) < FundCommunityPoolReturnStaticSize {
		return fmt.Errorf("insufficient data for FundCommunityPoolReturn")
	}

	// t.Success (static)
	t.Success = data0[0+31] == 1

	return nil
}

const SetWithdrawAddressCallStaticSize = 64

// SetWithdrawAddressCall represents an ABI tuple
type SetWithdrawAddressCall struct {
	DelegatorAddress  common.Address
	WithdrawerAddress string
}

// EncodedSize returns the total encoded size of SetWithdrawAddressCall
func (t SetWithdrawAddressCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.WithdrawerAddress)) // length + padded string data

	return SetWithdrawAddressCallStaticSize + dynamicSize
}

// EncodeTo encodes SetWithdrawAddressCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t SetWithdrawAddressCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := SetWithdrawAddressCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])

	// WithdrawerAddress (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// WithdrawerAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.WithdrawerAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.WithdrawerAddress))
	dynamicOffset += abi.Pad32(len(t.WithdrawerAddress))

	return dynamicOffset, nil
}

// Encode encodes SetWithdrawAddressCall to ABI bytes
func (t SetWithdrawAddressCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes SetWithdrawAddressCall from ABI bytes in the provided buffer
func (t *SetWithdrawAddressCall) Decode(data0 []byte) error {
	if len(data0) < SetWithdrawAddressCallStaticSize {
		return fmt.Errorf("insufficient data for SetWithdrawAddressCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])
	// WithdrawerAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.WithdrawerAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.WithdrawerAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes setWithdrawAddress arguments to ABI bytes including function selector
func (t SetWithdrawAddressCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], SetWithdrawAddressSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const SetWithdrawAddressReturnStaticSize = 32

// SetWithdrawAddressReturn represents an ABI tuple
type SetWithdrawAddressReturn struct {
	Success bool
}

// EncodedSize returns the total encoded size of SetWithdrawAddressReturn
func (t SetWithdrawAddressReturn) EncodedSize() int {
	dynamicSize := 0

	return SetWithdrawAddressReturnStaticSize + dynamicSize
}

// EncodeTo encodes SetWithdrawAddressReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t SetWithdrawAddressReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := SetWithdrawAddressReturnStaticSize // Start dynamic data after static section

	// Success (static)

	if t.Success {
		buf[0+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes SetWithdrawAddressReturn to ABI bytes
func (t SetWithdrawAddressReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes SetWithdrawAddressReturn from ABI bytes in the provided buffer
func (t *SetWithdrawAddressReturn) Decode(data0 []byte) error {
	if len(data0) < SetWithdrawAddressReturnStaticSize {
		return fmt.Errorf("insufficient data for SetWithdrawAddressReturn")
	}

	// t.Success (static)
	t.Success = data0[0+31] == 1

	return nil
}

const ValidatorCommissionCallStaticSize = 32

// ValidatorCommissionCall represents an ABI tuple
type ValidatorCommissionCall struct {
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of ValidatorCommissionCall
func (t ValidatorCommissionCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data

	return ValidatorCommissionCallStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorCommissionCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorCommissionCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorCommissionCallStaticSize // Start dynamic data after static section

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	return dynamicOffset, nil
}

// Encode encodes ValidatorCommissionCall to ABI bytes
func (t ValidatorCommissionCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorCommissionCall from ABI bytes in the provided buffer
func (t *ValidatorCommissionCall) Decode(data0 []byte) error {
	if len(data0) < ValidatorCommissionCallStaticSize {
		return fmt.Errorf("insufficient data for ValidatorCommissionCall")
	}

	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes validatorCommission arguments to ABI bytes including function selector
func (t ValidatorCommissionCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ValidatorCommissionSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const ValidatorCommissionReturnStaticSize = 32

// ValidatorCommissionReturn represents an ABI tuple
type ValidatorCommissionReturn struct {
	Commission []cmn.DecCoin
}

// EncodedSize returns the total encoded size of ValidatorCommissionReturn
func (t ValidatorCommissionReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Commission) // length + offset pointers for dynamic elements
	for _, elem := range t.Commission {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return ValidatorCommissionReturnStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorCommissionReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorCommissionReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorCommissionReturnStaticSize // Start dynamic data after static section

	// Commission (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Commission (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Commission)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Commission) * 32 // start after static region

			var offset int
			for _, item := range t.Commission {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorCommissionReturn to ABI bytes
func (t ValidatorCommissionReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorCommissionReturn from ABI bytes in the provided buffer
func (t *ValidatorCommissionReturn) Decode(data0 []byte) error {
	if len(data0) < ValidatorCommissionReturnStaticSize {
		return fmt.Errorf("insufficient data for ValidatorCommissionReturn")
	}

	// Commission
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Commission (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Commission = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Commission[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Commission[i0]")
			}
			if err := t.Commission[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const ValidatorDistributionInfoCallStaticSize = 32

// ValidatorDistributionInfoCall represents an ABI tuple
type ValidatorDistributionInfoCall struct {
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of ValidatorDistributionInfoCall
func (t ValidatorDistributionInfoCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data

	return ValidatorDistributionInfoCallStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorDistributionInfoCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorDistributionInfoCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorDistributionInfoCallStaticSize // Start dynamic data after static section

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	return dynamicOffset, nil
}

// Encode encodes ValidatorDistributionInfoCall to ABI bytes
func (t ValidatorDistributionInfoCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorDistributionInfoCall from ABI bytes in the provided buffer
func (t *ValidatorDistributionInfoCall) Decode(data0 []byte) error {
	if len(data0) < ValidatorDistributionInfoCallStaticSize {
		return fmt.Errorf("insufficient data for ValidatorDistributionInfoCall")
	}

	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes validatorDistributionInfo arguments to ABI bytes including function selector
func (t ValidatorDistributionInfoCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ValidatorDistributionInfoSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const ValidatorDistributionInfoReturnStaticSize = 32

// ValidatorDistributionInfoReturn represents an ABI tuple
type ValidatorDistributionInfoReturn struct {
	DistributionInfo ValidatorDistributionInfo
}

// EncodedSize returns the total encoded size of ValidatorDistributionInfoReturn
func (t ValidatorDistributionInfoReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += t.DistributionInfo.EncodedSize() // dynamic tuple

	return ValidatorDistributionInfoReturnStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorDistributionInfoReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorDistributionInfoReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorDistributionInfoReturnStaticSize // Start dynamic data after static section

	// DistributionInfo (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// DistributionInfo (dynamic)
	{
		n, err := t.DistributionInfo.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorDistributionInfoReturn to ABI bytes
func (t ValidatorDistributionInfoReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorDistributionInfoReturn from ABI bytes in the provided buffer
func (t *ValidatorDistributionInfoReturn) Decode(data0 []byte) error {
	if len(data0) < ValidatorDistributionInfoReturnStaticSize {
		return fmt.Errorf("insufficient data for ValidatorDistributionInfoReturn")
	}

	// DistributionInfo
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.DistributionInfo (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.DistributionInfo")
		}
		if err := t.DistributionInfo.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

const ValidatorOutstandingRewardsCallStaticSize = 32

// ValidatorOutstandingRewardsCall represents an ABI tuple
type ValidatorOutstandingRewardsCall struct {
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of ValidatorOutstandingRewardsCall
func (t ValidatorOutstandingRewardsCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data

	return ValidatorOutstandingRewardsCallStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorOutstandingRewardsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorOutstandingRewardsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorOutstandingRewardsCallStaticSize // Start dynamic data after static section

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	return dynamicOffset, nil
}

// Encode encodes ValidatorOutstandingRewardsCall to ABI bytes
func (t ValidatorOutstandingRewardsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorOutstandingRewardsCall from ABI bytes in the provided buffer
func (t *ValidatorOutstandingRewardsCall) Decode(data0 []byte) error {
	if len(data0) < ValidatorOutstandingRewardsCallStaticSize {
		return fmt.Errorf("insufficient data for ValidatorOutstandingRewardsCall")
	}

	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes validatorOutstandingRewards arguments to ABI bytes including function selector
func (t ValidatorOutstandingRewardsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ValidatorOutstandingRewardsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const ValidatorOutstandingRewardsReturnStaticSize = 32

// ValidatorOutstandingRewardsReturn represents an ABI tuple
type ValidatorOutstandingRewardsReturn struct {
	Rewards []cmn.DecCoin
}

// EncodedSize returns the total encoded size of ValidatorOutstandingRewardsReturn
func (t ValidatorOutstandingRewardsReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Rewards) // length + offset pointers for dynamic elements
	for _, elem := range t.Rewards {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return ValidatorOutstandingRewardsReturnStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorOutstandingRewardsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorOutstandingRewardsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorOutstandingRewardsReturnStaticSize // Start dynamic data after static section

	// Rewards (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Rewards (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Rewards)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Rewards) * 32 // start after static region

			var offset int
			for _, item := range t.Rewards {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorOutstandingRewardsReturn to ABI bytes
func (t ValidatorOutstandingRewardsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorOutstandingRewardsReturn from ABI bytes in the provided buffer
func (t *ValidatorOutstandingRewardsReturn) Decode(data0 []byte) error {
	if len(data0) < ValidatorOutstandingRewardsReturnStaticSize {
		return fmt.Errorf("insufficient data for ValidatorOutstandingRewardsReturn")
	}

	// Rewards
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Rewards (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Rewards = make([]cmn.DecCoin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Rewards[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Rewards[i0]")
			}
			if err := t.Rewards[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const ValidatorSlashesCallStaticSize = 128

// ValidatorSlashesCall represents an ABI tuple
type ValidatorSlashesCall struct {
	ValidatorAddress string
	StartingHeight   uint64
	EndingHeight     uint64
	PageRequest      PageRequest
}

// EncodedSize returns the total encoded size of ValidatorSlashesCall
func (t ValidatorSlashesCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data
	dynamicSize += t.PageRequest.EncodedSize()             // dynamic tuple

	return ValidatorSlashesCallStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorSlashesCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorSlashesCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorSlashesCallStaticSize // Start dynamic data after static section

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	// StartingHeight (static)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(t.StartingHeight))
	// EndingHeight (static)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(t.EndingHeight))

	// PageRequest (offset)
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(dynamicOffset))

	// PageRequest (dynamic)
	{
		n, err := t.PageRequest.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorSlashesCall to ABI bytes
func (t ValidatorSlashesCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorSlashesCall from ABI bytes in the provided buffer
func (t *ValidatorSlashesCall) Decode(data0 []byte) error {
	if len(data0) < ValidatorSlashesCallStaticSize {
		return fmt.Errorf("insufficient data for ValidatorSlashesCall")
	}

	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}
	// t.StartingHeight (static)
	t.StartingHeight = uint64(binary.BigEndian.Uint64(data0[32+24 : 32+32]))
	// t.EndingHeight (static)
	t.EndingHeight = uint64(binary.BigEndian.Uint64(data0[64+24 : 64+32]))
	// PageRequest
	{
		offset := int(binary.BigEndian.Uint64(data0[96+24 : 96+32]))

		// t.PageRequest (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.PageRequest")
		}
		if err := t.PageRequest.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

// EncodeWithSelector encodes validatorSlashes arguments to ABI bytes including function selector
func (t ValidatorSlashesCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], ValidatorSlashesSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const ValidatorSlashesReturnStaticSize = 64

// ValidatorSlashesReturn represents an ABI tuple
type ValidatorSlashesReturn struct {
	Slashes      []ValidatorSlashEvent
	PageResponse PageResponse
}

// EncodedSize returns the total encoded size of ValidatorSlashesReturn
func (t ValidatorSlashesReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 96*len(t.Slashes)       // length + static elements
	dynamicSize += t.PageResponse.EncodedSize() // dynamic tuple

	return ValidatorSlashesReturnStaticSize + dynamicSize
}

// EncodeTo encodes ValidatorSlashesReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t ValidatorSlashesReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ValidatorSlashesReturnStaticSize // Start dynamic data after static section

	// Slashes (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Slashes (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Slashes)))
		dynamicOffset += 32

		// data without dynamic region
		buf := buf[dynamicOffset:]
		var offset int
		for _, item := range t.Slashes {

			// Encode nested tuple item
			if _, err := item.EncodeTo(buf[offset:]); err != nil {
				return 0, err
			}

			offset += 96
		}
		dynamicOffset += offset

	}

	// PageResponse (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// PageResponse (dynamic)
	{
		n, err := t.PageResponse.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes ValidatorSlashesReturn to ABI bytes
func (t ValidatorSlashesReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ValidatorSlashesReturn from ABI bytes in the provided buffer
func (t *ValidatorSlashesReturn) Decode(data0 []byte) error {
	if len(data0) < ValidatorSlashesReturnStaticSize {
		return fmt.Errorf("insufficient data for ValidatorSlashesReturn")
	}

	// Slashes
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Slashes (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Slashes = make([]ValidatorSlashEvent, length)
		data1 := data0[offset:]

		offset = 0
		for i0 := 0; i0 < length; i0++ {
			// t.Slashes[i0] (static)
			if err := t.Slashes[i0].Decode(data1[offset : offset+96]); err != nil {
				return err
			}
			offset += 96
		}
	}
	// PageResponse
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.PageResponse (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.PageResponse")
		}
		if err := t.PageResponse.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

const WithdrawDelegatorRewardsCallStaticSize = 64

// WithdrawDelegatorRewardsCall represents an ABI tuple
type WithdrawDelegatorRewardsCall struct {
	DelegatorAddress common.Address
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of WithdrawDelegatorRewardsCall
func (t WithdrawDelegatorRewardsCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data

	return WithdrawDelegatorRewardsCallStaticSize + dynamicSize
}

// EncodeTo encodes WithdrawDelegatorRewardsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t WithdrawDelegatorRewardsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := WithdrawDelegatorRewardsCallStaticSize // Start dynamic data after static section

	// DelegatorAddress (static)
	copy(buf[0+12:0+32], t.DelegatorAddress[:])

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	return dynamicOffset, nil
}

// Encode encodes WithdrawDelegatorRewardsCall to ABI bytes
func (t WithdrawDelegatorRewardsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes WithdrawDelegatorRewardsCall from ABI bytes in the provided buffer
func (t *WithdrawDelegatorRewardsCall) Decode(data0 []byte) error {
	if len(data0) < WithdrawDelegatorRewardsCallStaticSize {
		return fmt.Errorf("insufficient data for WithdrawDelegatorRewardsCall")
	}

	// t.DelegatorAddress (static)
	copy(t.DelegatorAddress[:], data0[0+12:0+32])
	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes withdrawDelegatorRewards arguments to ABI bytes including function selector
func (t WithdrawDelegatorRewardsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], WithdrawDelegatorRewardsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const WithdrawDelegatorRewardsReturnStaticSize = 32

// WithdrawDelegatorRewardsReturn represents an ABI tuple
type WithdrawDelegatorRewardsReturn struct {
	Amount []cmn.Coin
}

// EncodedSize returns the total encoded size of WithdrawDelegatorRewardsReturn
func (t WithdrawDelegatorRewardsReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Amount) // length + offset pointers for dynamic elements
	for _, elem := range t.Amount {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return WithdrawDelegatorRewardsReturnStaticSize + dynamicSize
}

// EncodeTo encodes WithdrawDelegatorRewardsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t WithdrawDelegatorRewardsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := WithdrawDelegatorRewardsReturnStaticSize // Start dynamic data after static section

	// Amount (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Amount (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Amount)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Amount) * 32 // start after static region

			var offset int
			for _, item := range t.Amount {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes WithdrawDelegatorRewardsReturn to ABI bytes
func (t WithdrawDelegatorRewardsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes WithdrawDelegatorRewardsReturn from ABI bytes in the provided buffer
func (t *WithdrawDelegatorRewardsReturn) Decode(data0 []byte) error {
	if len(data0) < WithdrawDelegatorRewardsReturnStaticSize {
		return fmt.Errorf("insufficient data for WithdrawDelegatorRewardsReturn")
	}

	// Amount
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Amount (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Amount = make([]cmn.Coin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Amount[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Amount[i0]")
			}
			if err := t.Amount[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const WithdrawValidatorCommissionCallStaticSize = 32

// WithdrawValidatorCommissionCall represents an ABI tuple
type WithdrawValidatorCommissionCall struct {
	ValidatorAddress string
}

// EncodedSize returns the total encoded size of WithdrawValidatorCommissionCall
func (t WithdrawValidatorCommissionCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.ValidatorAddress)) // length + padded string data

	return WithdrawValidatorCommissionCallStaticSize + dynamicSize
}

// EncodeTo encodes WithdrawValidatorCommissionCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t WithdrawValidatorCommissionCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := WithdrawValidatorCommissionCallStaticSize // Start dynamic data after static section

	// ValidatorAddress (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// ValidatorAddress (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ValidatorAddress)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ValidatorAddress))
	dynamicOffset += abi.Pad32(len(t.ValidatorAddress))

	return dynamicOffset, nil
}

// Encode encodes WithdrawValidatorCommissionCall to ABI bytes
func (t WithdrawValidatorCommissionCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes WithdrawValidatorCommissionCall from ABI bytes in the provided buffer
func (t *WithdrawValidatorCommissionCall) Decode(data0 []byte) error {
	if len(data0) < WithdrawValidatorCommissionCallStaticSize {
		return fmt.Errorf("insufficient data for WithdrawValidatorCommissionCall")
	}

	// ValidatorAddress
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.ValidatorAddress (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ValidatorAddress = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes withdrawValidatorCommission arguments to ABI bytes including function selector
func (t WithdrawValidatorCommissionCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], WithdrawValidatorCommissionSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const WithdrawValidatorCommissionReturnStaticSize = 32

// WithdrawValidatorCommissionReturn represents an ABI tuple
type WithdrawValidatorCommissionReturn struct {
	Amount []cmn.Coin
}

// EncodedSize returns the total encoded size of WithdrawValidatorCommissionReturn
func (t WithdrawValidatorCommissionReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Amount) // length + offset pointers for dynamic elements
	for _, elem := range t.Amount {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return WithdrawValidatorCommissionReturnStaticSize + dynamicSize
}

// EncodeTo encodes WithdrawValidatorCommissionReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t WithdrawValidatorCommissionReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := WithdrawValidatorCommissionReturnStaticSize // Start dynamic data after static section

	// Amount (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Amount (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Amount)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Amount) * 32 // start after static region

			var offset int
			for _, item := range t.Amount {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes WithdrawValidatorCommissionReturn to ABI bytes
func (t WithdrawValidatorCommissionReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes WithdrawValidatorCommissionReturn from ABI bytes in the provided buffer
func (t *WithdrawValidatorCommissionReturn) Decode(data0 []byte) error {
	if len(data0) < WithdrawValidatorCommissionReturnStaticSize {
		return fmt.Errorf("insufficient data for WithdrawValidatorCommissionReturn")
	}

	// Amount
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Amount (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Amount = make([]cmn.Coin, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset
			// t.Amount[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Amount[i0]")
			}
			if err := t.Amount[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}
