// Code generated by go-abi. DO NOT EDIT.

package bank

import (
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// balances(address)
	BalancesSelector = [4]byte{0x27, 0xe2, 0x35, 0xe3}
	// supplyOf(address)
	SupplyOfSelector = [4]byte{0x62, 0x40, 0x0e, 0x4c}
	// totalSupply()
	TotalSupplySelector = [4]byte{0x18, 0x16, 0x0d, 0xdd}
)

// Big endian integer versions of function selectors
const (
	BalancesID    = 669136355
	SupplyOfID    = 1648365132
	TotalSupplyID = 404098525
)

const BalanceStaticSize = 64

// Balance represents an ABI tuple
type Balance struct {
	ContractAddress common.Address
	Amount          *big.Int
}

// EncodedSize returns the total encoded size of Balance
func (t Balance) EncodedSize() int {
	dynamicSize := 0

	return BalanceStaticSize + dynamicSize
}

// EncodeTo encodes Balance to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Balance) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := BalanceStaticSize // Start dynamic data after static section

	// ContractAddress (static)
	copy(buf[0+12:0+32], t.ContractAddress[:])
	// Amount (static)

	if err := abi.EncodeBigInt(t.Amount, buf[32:64], false); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes Balance to ABI bytes
func (t Balance) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Balance from ABI bytes in the provided buffer
func (t *Balance) Decode(data0 []byte) error {
	if len(data0) < BalanceStaticSize {
		return fmt.Errorf("insufficient data for Balance")
	}

	// t.ContractAddress (static)
	copy(t.ContractAddress[:], data0[0+12:0+32])
	// t.Amount (static)
	t.Amount = new(big.Int).SetBytes(data0[32:64])

	return nil
}

const BalancesCallStaticSize = 32

// BalancesCall represents an ABI tuple
type BalancesCall struct {
	Account common.Address
}

// EncodedSize returns the total encoded size of BalancesCall
func (t BalancesCall) EncodedSize() int {
	dynamicSize := 0

	return BalancesCallStaticSize + dynamicSize
}

// EncodeTo encodes BalancesCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t BalancesCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := BalancesCallStaticSize // Start dynamic data after static section

	// Account (static)
	copy(buf[0+12:0+32], t.Account[:])

	return dynamicOffset, nil
}

// Encode encodes BalancesCall to ABI bytes
func (t BalancesCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes BalancesCall from ABI bytes in the provided buffer
func (t *BalancesCall) Decode(data0 []byte) error {
	if len(data0) < BalancesCallStaticSize {
		return fmt.Errorf("insufficient data for BalancesCall")
	}

	// t.Account (static)
	copy(t.Account[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes balances arguments to ABI bytes including function selector
func (t BalancesCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], BalancesSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const BalancesReturnStaticSize = 32

// BalancesReturn represents an ABI tuple
type BalancesReturn struct {
	Balances []Balance
}

// EncodedSize returns the total encoded size of BalancesReturn
func (t BalancesReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 64*len(t.Balances) // length + static elements

	return BalancesReturnStaticSize + dynamicSize
}

// EncodeTo encodes BalancesReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t BalancesReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := BalancesReturnStaticSize // Start dynamic data after static section

	// Balances (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Balances (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Balances)))
		dynamicOffset += 32

		// data without dynamic region
		buf := buf[dynamicOffset:]
		var offset int
		for _, item := range t.Balances {

			// Encode nested tuple item
			if _, err := item.EncodeTo(buf[offset:]); err != nil {
				return 0, err
			}

			offset += 64
		}
		dynamicOffset += offset

	}

	return dynamicOffset, nil
}

// Encode encodes BalancesReturn to ABI bytes
func (t BalancesReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes BalancesReturn from ABI bytes in the provided buffer
func (t *BalancesReturn) Decode(data0 []byte) error {
	if len(data0) < BalancesReturnStaticSize {
		return fmt.Errorf("insufficient data for BalancesReturn")
	}

	// Balances
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Balances (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Balances = make([]Balance, length)
		data1 := data0[offset:]

		offset = 0
		for i0 := 0; i0 < length; i0++ {
			// t.Balances[i0] (static)
			if err := t.Balances[i0].Decode(data1[offset : offset+64]); err != nil {
				return err
			}
			offset += 64
		}
	}

	return nil
}

const SupplyOfCallStaticSize = 32

// SupplyOfCall represents an ABI tuple
type SupplyOfCall struct {
	Erc20Address common.Address
}

// EncodedSize returns the total encoded size of SupplyOfCall
func (t SupplyOfCall) EncodedSize() int {
	dynamicSize := 0

	return SupplyOfCallStaticSize + dynamicSize
}

// EncodeTo encodes SupplyOfCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t SupplyOfCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := SupplyOfCallStaticSize // Start dynamic data after static section

	// Erc20Address (static)
	copy(buf[0+12:0+32], t.Erc20Address[:])

	return dynamicOffset, nil
}

// Encode encodes SupplyOfCall to ABI bytes
func (t SupplyOfCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes SupplyOfCall from ABI bytes in the provided buffer
func (t *SupplyOfCall) Decode(data0 []byte) error {
	if len(data0) < SupplyOfCallStaticSize {
		return fmt.Errorf("insufficient data for SupplyOfCall")
	}

	// t.Erc20Address (static)
	copy(t.Erc20Address[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes supplyOf arguments to ABI bytes including function selector
func (t SupplyOfCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], SupplyOfSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const SupplyOfReturnStaticSize = 32

// SupplyOfReturn represents an ABI tuple
type SupplyOfReturn struct {
	TotalSupply *big.Int
}

// EncodedSize returns the total encoded size of SupplyOfReturn
func (t SupplyOfReturn) EncodedSize() int {
	dynamicSize := 0

	return SupplyOfReturnStaticSize + dynamicSize
}

// EncodeTo encodes SupplyOfReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t SupplyOfReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := SupplyOfReturnStaticSize // Start dynamic data after static section

	// TotalSupply (static)

	if err := abi.EncodeBigInt(t.TotalSupply, buf[0:32], false); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes SupplyOfReturn to ABI bytes
func (t SupplyOfReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes SupplyOfReturn from ABI bytes in the provided buffer
func (t *SupplyOfReturn) Decode(data0 []byte) error {
	if len(data0) < SupplyOfReturnStaticSize {
		return fmt.Errorf("insufficient data for SupplyOfReturn")
	}

	// t.TotalSupply (static)
	t.TotalSupply = new(big.Int).SetBytes(data0[0:32])

	return nil
}

const TotalSupplyReturnStaticSize = 32

// TotalSupplyReturn represents an ABI tuple
type TotalSupplyReturn struct {
	TotalSupply []Balance
}

// EncodedSize returns the total encoded size of TotalSupplyReturn
func (t TotalSupplyReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 64*len(t.TotalSupply) // length + static elements

	return TotalSupplyReturnStaticSize + dynamicSize
}

// EncodeTo encodes TotalSupplyReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t TotalSupplyReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := TotalSupplyReturnStaticSize // Start dynamic data after static section

	// TotalSupply (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// TotalSupply (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.TotalSupply)))
		dynamicOffset += 32

		// data without dynamic region
		buf := buf[dynamicOffset:]
		var offset int
		for _, item := range t.TotalSupply {

			// Encode nested tuple item
			if _, err := item.EncodeTo(buf[offset:]); err != nil {
				return 0, err
			}

			offset += 64
		}
		dynamicOffset += offset

	}

	return dynamicOffset, nil
}

// Encode encodes TotalSupplyReturn to ABI bytes
func (t TotalSupplyReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TotalSupplyReturn from ABI bytes in the provided buffer
func (t *TotalSupplyReturn) Decode(data0 []byte) error {
	if len(data0) < TotalSupplyReturnStaticSize {
		return fmt.Errorf("insufficient data for TotalSupplyReturn")
	}

	// TotalSupply
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.TotalSupply (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.TotalSupply = make([]Balance, length)
		data1 := data0[offset:]

		offset = 0
		for i0 := 0; i0 < length; i0++ {
			// t.TotalSupply[i0] (static)
			if err := t.TotalSupply[i0].Decode(data1[offset : offset+64]); err != nil {
				return err
			}
			offset += 64
		}
	}

	return nil
}
