// Code generated by go-abi. DO NOT EDIT.

package ics20

import (
	"encoding/binary"
	"fmt"
	"math/big"

	cmn "github.com/cosmos/evm/precompiles/common"
	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// denom(string)
	DenomSelector = [4]byte{0x5f, 0x1f, 0x98, 0xa2}
	// denomHash(string)
	DenomHashSelector = [4]byte{0xb5, 0xcb, 0x6e, 0x7d}
	// denoms((bytes,uint64,uint64,bool,bool))
	DenomsSelector = [4]byte{0xc0, 0xfa, 0xb1, 0x04}
	// transfer(string,string,string,uint256,address,string,(uint64,uint64),uint64,string)
	TransferSelector = [4]byte{0x63, 0x25, 0x35, 0xb9}
)

// Big endian integer versions of function selectors
const (
	DenomID     = 1595906210
	DenomHashID = 3050008189
	DenomsID    = 3237654788
	TransferID  = 1663382969
)

// Event signatures
var (
	// IBCTransfer(address,string,string,string,string,uint256,string)
	IBCTransferEventTopic = common.Hash{0xc0, 0x1e, 0xca, 0x5e, 0x74, 0x2f, 0xe6, 0x64, 0x1c, 0x4b, 0xe5, 0x01, 0xc2, 0xbe, 0xbf, 0x22, 0x44, 0x72, 0xf6, 0x91, 0x76, 0xa0, 0x55, 0x2e, 0x87, 0xe3, 0x01, 0x47, 0xa6, 0x41, 0x13, 0x03}
)

const DenomStaticSize = 64

// Denom represents an ABI tuple
type Denom struct {
	Base  string
	Trace []Hop
}

// EncodedSize returns the total encoded size of Denom
func (t Denom) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Base)) // length + padded string data
	dynamicSize += 32 + 32*len(t.Trace)        // length + offset pointers for dynamic elements
	for _, elem := range t.Trace {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}

	return DenomStaticSize + dynamicSize
}

// EncodeTo encodes Denom to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Denom) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomStaticSize // Start dynamic data after static section

	// Base (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Base (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Base)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Base))
	dynamicOffset += abi.Pad32(len(t.Base))

	// Trace (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// Trace (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Trace)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Trace) * 32 // start after static region

			var offset int
			for _, item := range t.Trace {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	return dynamicOffset, nil
}

// Encode encodes Denom to ABI bytes
func (t Denom) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Denom from ABI bytes in the provided buffer
func (t *Denom) Decode(data0 []byte) error {
	if len(data0) < DenomStaticSize {
		return fmt.Errorf("insufficient data for Denom")
	}

	// Base
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Base (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Base = string(data0[offset : offset+length])
	}
	// Trace
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.Trace (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Trace = make([]Hop, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset

			// t.Trace[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Trace[i0]")
			}
			if err := t.Trace[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}

	return nil
}

const HopStaticSize = 64

// Hop represents an ABI tuple
type Hop struct {
	PortId    string
	ChannelId string
}

// EncodedSize returns the total encoded size of Hop
func (t Hop) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.PortId))    // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.ChannelId)) // length + padded string data

	return HopStaticSize + dynamicSize
}

// EncodeTo encodes Hop to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Hop) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := HopStaticSize // Start dynamic data after static section

	// PortId (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// PortId (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.PortId)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.PortId))
	dynamicOffset += abi.Pad32(len(t.PortId))

	// ChannelId (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// ChannelId (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.ChannelId)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.ChannelId))
	dynamicOffset += abi.Pad32(len(t.ChannelId))

	return dynamicOffset, nil
}

// Encode encodes Hop to ABI bytes
func (t Hop) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Hop from ABI bytes in the provided buffer
func (t *Hop) Decode(data0 []byte) error {
	if len(data0) < HopStaticSize {
		return fmt.Errorf("insufficient data for Hop")
	}

	// PortId
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.PortId (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.PortId = string(data0[offset : offset+length])
	}
	// ChannelId
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.ChannelId (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.ChannelId = string(data0[offset : offset+length])
	}

	return nil
}

const DenomCallStaticSize = 32

// DenomCall represents an ABI tuple
type DenomCall struct {
	Hash string
}

// EncodedSize returns the total encoded size of DenomCall
func (t DenomCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Hash)) // length + padded string data

	return DenomCallStaticSize + dynamicSize
}

// EncodeTo encodes DenomCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DenomCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomCallStaticSize // Start dynamic data after static section

	// Hash (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Hash (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Hash)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Hash))
	dynamicOffset += abi.Pad32(len(t.Hash))

	return dynamicOffset, nil
}

// Encode encodes DenomCall to ABI bytes
func (t DenomCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DenomCall from ABI bytes in the provided buffer
func (t *DenomCall) Decode(data0 []byte) error {
	if len(data0) < DenomCallStaticSize {
		return fmt.Errorf("insufficient data for DenomCall")
	}

	// Hash
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Hash (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Hash = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes denom arguments to ABI bytes including function selector
func (t DenomCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DenomSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DenomReturnStaticSize = 32

// DenomReturn represents an ABI tuple
type DenomReturn struct {
	Denom Denom
}

// EncodedSize returns the total encoded size of DenomReturn
func (t DenomReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += t.Denom.EncodedSize() // dynamic tuple

	return DenomReturnStaticSize + dynamicSize
}

// EncodeTo encodes DenomReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DenomReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomReturnStaticSize // Start dynamic data after static section

	// Denom (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Denom (dynamic)
	{
		n, err := t.Denom.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes DenomReturn to ABI bytes
func (t DenomReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DenomReturn from ABI bytes in the provided buffer
func (t *DenomReturn) Decode(data0 []byte) error {
	if len(data0) < DenomReturnStaticSize {
		return fmt.Errorf("insufficient data for DenomReturn")
	}

	// Denom
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Denom (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.Denom")
		}
		if err := t.Denom.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

const DenomHashCallStaticSize = 32

// DenomHashCall represents an ABI tuple
type DenomHashCall struct {
	Trace string
}

// EncodedSize returns the total encoded size of DenomHashCall
func (t DenomHashCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Trace)) // length + padded string data

	return DenomHashCallStaticSize + dynamicSize
}

// EncodeTo encodes DenomHashCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DenomHashCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomHashCallStaticSize // Start dynamic data after static section

	// Trace (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Trace (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Trace)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Trace))
	dynamicOffset += abi.Pad32(len(t.Trace))

	return dynamicOffset, nil
}

// Encode encodes DenomHashCall to ABI bytes
func (t DenomHashCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DenomHashCall from ABI bytes in the provided buffer
func (t *DenomHashCall) Decode(data0 []byte) error {
	if len(data0) < DenomHashCallStaticSize {
		return fmt.Errorf("insufficient data for DenomHashCall")
	}

	// Trace
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Trace (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Trace = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes denomHash arguments to ABI bytes including function selector
func (t DenomHashCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DenomHashSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DenomHashReturnStaticSize = 32

// DenomHashReturn represents an ABI tuple
type DenomHashReturn struct {
	Hash string
}

// EncodedSize returns the total encoded size of DenomHashReturn
func (t DenomHashReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Hash)) // length + padded string data

	return DenomHashReturnStaticSize + dynamicSize
}

// EncodeTo encodes DenomHashReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DenomHashReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomHashReturnStaticSize // Start dynamic data after static section

	// Hash (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Hash (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Hash)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Hash))
	dynamicOffset += abi.Pad32(len(t.Hash))

	return dynamicOffset, nil
}

// Encode encodes DenomHashReturn to ABI bytes
func (t DenomHashReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DenomHashReturn from ABI bytes in the provided buffer
func (t *DenomHashReturn) Decode(data0 []byte) error {
	if len(data0) < DenomHashReturnStaticSize {
		return fmt.Errorf("insufficient data for DenomHashReturn")
	}

	// Hash
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Hash (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Hash = string(data0[offset : offset+length])
	}

	return nil
}

const DenomsCallStaticSize = 32

// DenomsCall represents an ABI tuple
type DenomsCall struct {
	PageRequest cmn.PageRequest
}

// EncodedSize returns the total encoded size of DenomsCall
func (t DenomsCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += t.PageRequest.EncodedSize() // dynamic tuple

	return DenomsCallStaticSize + dynamicSize
}

// EncodeTo encodes DenomsCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DenomsCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomsCallStaticSize // Start dynamic data after static section

	// PageRequest (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// PageRequest (dynamic)
	{
		n, err := t.PageRequest.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes DenomsCall to ABI bytes
func (t DenomsCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DenomsCall from ABI bytes in the provided buffer
func (t *DenomsCall) Decode(data0 []byte) error {
	if len(data0) < DenomsCallStaticSize {
		return fmt.Errorf("insufficient data for DenomsCall")
	}

	// PageRequest
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.PageRequest (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.PageRequest")
		}
		if err := t.PageRequest.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

// EncodeWithSelector encodes denoms arguments to ABI bytes including function selector
func (t DenomsCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DenomsSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const DenomsReturnStaticSize = 64

// DenomsReturn represents an ABI tuple
type DenomsReturn struct {
	Denoms       []Denom
	PageResponse cmn.PageResponse
}

// EncodedSize returns the total encoded size of DenomsReturn
func (t DenomsReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 32*len(t.Denoms) // length + offset pointers for dynamic elements
	for _, elem := range t.Denoms {
		dynamicSize += elem.EncodedSize() // dynamic tuple
	}
	dynamicSize += t.PageResponse.EncodedSize() // dynamic tuple

	return DenomsReturnStaticSize + dynamicSize
}

// EncodeTo encodes DenomsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DenomsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DenomsReturnStaticSize // Start dynamic data after static section

	// Denoms (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Denoms (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Denoms)))
		dynamicOffset += 32

		var written int

		// data with dynamic region
		{
			buf := buf[dynamicOffset:]
			dynamicOffset := len(t.Denoms) * 32 // start after static region

			var offset int
			for _, item := range t.Denoms {
				// write offsets
				binary.BigEndian.PutUint64(buf[offset+24:offset+32], uint64(dynamicOffset))
				offset += 32

				// write data (dynamic)

				{
					n, err := item.EncodeTo(buf[dynamicOffset:])
					if err != nil {
						return 0, err
					}
					dynamicOffset += n
				}

			}
			written = dynamicOffset
		}
		dynamicOffset += written

	}

	// PageResponse (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// PageResponse (dynamic)
	{
		n, err := t.PageResponse.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes DenomsReturn to ABI bytes
func (t DenomsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DenomsReturn from ABI bytes in the provided buffer
func (t *DenomsReturn) Decode(data0 []byte) error {
	if len(data0) < DenomsReturnStaticSize {
		return fmt.Errorf("insufficient data for DenomsReturn")
	}

	// Denoms
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Denoms (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.Denoms = make([]Denom, length)
		data1 := data0[offset:]

		// Dynamic elements with offsets (dynamic array)
		for i0 := 0; i0 < length; i0++ {
			// Read element offset
			tmp := i0 * 32
			if tmp+32 > len(data1) {
				return fmt.Errorf("insufficient data for element offset")
			}
			offset := int(binary.BigEndian.Uint64(data1[tmp+24 : tmp+32]))
			// Decode dynamic element at offset

			// t.Denoms[i0] (dynamic)
			if offset >= len(data1) {
				return fmt.Errorf("insufficient data for dynamic data, t.Denoms[i0]")
			}
			if err := t.Denoms[i0].Decode(data1[offset:]); err != nil {
				return err
			}
		}
	}
	// PageResponse
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.PageResponse (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.PageResponse")
		}
		if err := t.PageResponse.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

const TransferCallStaticSize = 320

// TransferCall represents an ABI tuple
type TransferCall struct {
	SourcePort       string
	SourceChannel    string
	Denom            string
	Amount           *big.Int
	Sender           common.Address
	Receiver         string
	TimeoutHeight    cmn.Height
	TimeoutTimestamp uint64
	Memo             string
}

// EncodedSize returns the total encoded size of TransferCall
func (t TransferCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.SourcePort))    // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.SourceChannel)) // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.Denom))         // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.Receiver))      // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.Memo))          // length + padded string data

	return TransferCallStaticSize + dynamicSize
}

// EncodeTo encodes TransferCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t TransferCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := TransferCallStaticSize // Start dynamic data after static section

	// SourcePort (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// SourcePort (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.SourcePort)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.SourcePort))
	dynamicOffset += abi.Pad32(len(t.SourcePort))

	// SourceChannel (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// SourceChannel (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.SourceChannel)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.SourceChannel))
	dynamicOffset += abi.Pad32(len(t.SourceChannel))

	// Denom (offset)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))

	// Denom (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Denom)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Denom))
	dynamicOffset += abi.Pad32(len(t.Denom))

	// Amount (static)

	if err := abi.EncodeBigInt(t.Amount, buf[96:128], false); err != nil {
		return 0, err
	}

	// Sender (static)
	copy(buf[128+12:128+32], t.Sender[:])

	// Receiver (offset)
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(dynamicOffset))

	// Receiver (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Receiver)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Receiver))
	dynamicOffset += abi.Pad32(len(t.Receiver))

	// TimeoutHeight (static)
	// Encode nested tuple t.TimeoutHeight
	if _, err := t.TimeoutHeight.EncodeTo(buf[192:]); err != nil {
		return 0, err
	}

	// TimeoutTimestamp (static)
	binary.BigEndian.PutUint64(buf[256+24:256+32], uint64(t.TimeoutTimestamp))

	// Memo (offset)
	binary.BigEndian.PutUint64(buf[288+24:288+32], uint64(dynamicOffset))

	// Memo (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Memo)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Memo))
	dynamicOffset += abi.Pad32(len(t.Memo))

	return dynamicOffset, nil
}

// Encode encodes TransferCall to ABI bytes
func (t TransferCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferCall from ABI bytes in the provided buffer
func (t *TransferCall) Decode(data0 []byte) error {
	if len(data0) < TransferCallStaticSize {
		return fmt.Errorf("insufficient data for TransferCall")
	}

	// SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.SourcePort (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.SourcePort = string(data0[offset : offset+length])
	}
	// SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.SourceChannel (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.SourceChannel = string(data0[offset : offset+length])
	}
	// Denom
	{
		offset := int(binary.BigEndian.Uint64(data0[64+24 : 64+32]))

		// t.Denom (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Denom = string(data0[offset : offset+length])
	}
	// t.Amount (static)
	t.Amount = new(big.Int).SetBytes(data0[96:128])
	// t.Sender (static)
	copy(t.Sender[:], data0[128+12:128+32])
	// Receiver
	{
		offset := int(binary.BigEndian.Uint64(data0[160+24 : 160+32]))

		// t.Receiver (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Receiver = string(data0[offset : offset+length])
	}
	// t.TimeoutHeight (static)
	if err := t.TimeoutHeight.Decode(data0[192:256]); err != nil {
		return err
	}
	// t.TimeoutTimestamp (static)
	t.TimeoutTimestamp = uint64(binary.BigEndian.Uint64(data0[256+24 : 256+32]))
	// Memo
	{
		offset := int(binary.BigEndian.Uint64(data0[288+24 : 288+32]))

		// t.Memo (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Memo = string(data0[offset : offset+length])
	}

	return nil
}

// EncodeWithSelector encodes transfer arguments to ABI bytes including function selector
func (t TransferCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], TransferSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const TransferReturnStaticSize = 32

// TransferReturn represents an ABI tuple
type TransferReturn struct {
	NextSequence uint64
}

// EncodedSize returns the total encoded size of TransferReturn
func (t TransferReturn) EncodedSize() int {
	dynamicSize := 0

	return TransferReturnStaticSize + dynamicSize
}

// EncodeTo encodes TransferReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t TransferReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := TransferReturnStaticSize // Start dynamic data after static section

	// NextSequence (static)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(t.NextSequence))

	return dynamicOffset, nil
}

// Encode encodes TransferReturn to ABI bytes
func (t TransferReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes TransferReturn from ABI bytes in the provided buffer
func (t *TransferReturn) Decode(data0 []byte) error {
	if len(data0) < TransferReturnStaticSize {
		return fmt.Errorf("insufficient data for TransferReturn")
	}

	// t.NextSequence (static)
	t.NextSequence = uint64(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

	return nil
}

// IBCTransferEvent represents an ABI event
type IBCTransferEvent struct {
	IBCTransferEventIndexed
	IBCTransferEventData
}

// NewIBCTransferEvent constructs a new IBCTransfer event
func NewIBCTransferEvent(
	sender common.Address,
	receiver string,
	sourcePort string,
	sourceChannel string,
	denom string,
	amount *big.Int,
	memo string,
) IBCTransferEvent {
	return IBCTransferEvent{
		IBCTransferEventIndexed: IBCTransferEventIndexed{
			Sender:   sender,
			Receiver: receiver,
		},
		IBCTransferEventData: IBCTransferEventData{
			SourcePort:    sourcePort,
			SourceChannel: sourceChannel,
			Denom:         denom,
			Amount:        amount,
			Memo:          memo,
		},
	}
}

// IBCTransfer represents an ABI event
type IBCTransferEventIndexed struct {
	Sender   common.Address
	Receiver string
}

// EncodeTopics encodes indexed fields of IBCTransfer event to topics
func (e IBCTransferEventIndexed) EncodeTopics() []common.Hash {
	topics := make([]common.Hash, 0, 3)
	topics = append(topics, IBCTransferEventTopic)

	// Encode indexed field Sender
	{
		var buf common.Hash

		// Sender (static)
		copy(buf[0+12:0+32], e.Sender[:])

		topics = append(topics, buf)
	}

	// Encode indexed field Receiver
	{
		var buf common.Hash

		// Receiver (dynamic)
		// length
		binary.BigEndian.PutUint64(buf[24:32], uint64(len(e.Receiver)))
		// data
		copy(buf[32:], []byte(e.Receiver))

		topics = append(topics, buf)
	}

	return topics
}

// DecodeTopics decodes indexed fields of IBCTransfer event from topics
func (e *IBCTransferEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) < 3 {
		return fmt.Errorf("insufficient topics for IBCTransfer event")
	}

	// Check event signature
	if topics[0] != IBCTransferEventTopic {
		return fmt.Errorf("invalid event signature for IBCTransfer event")
	}

	// Sender (static)
	{
		data := topics[1][:]
		offset := 0

		// e.Sender (static)
		copy(e.Sender[:], data[offset+12:offset+32])

	}

	// Receiver (dynamic)
	{
		data := topics[2][:]
		offset := 0

		// e.Receiver (dynamic)
		if offset+32 > len(data) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data[offset+24 : offset+32]))
		offset += 32
		// string data
		e.Receiver = string(data[offset : offset+length])

	}

	return nil
}

const IBCTransferEventDataStaticSize = 160

// IBCTransferEventData represents an ABI tuple
type IBCTransferEventData struct {
	SourcePort    string
	SourceChannel string
	Denom         string
	Amount        *big.Int
	Memo          string
}

// EncodedSize returns the total encoded size of IBCTransferEventData
func (t IBCTransferEventData) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.SourcePort))    // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.SourceChannel)) // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.Denom))         // length + padded string data
	dynamicSize += 32 + abi.Pad32(len(t.Memo))          // length + padded string data

	return IBCTransferEventDataStaticSize + dynamicSize
}

// EncodeTo encodes IBCTransferEventData to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t IBCTransferEventData) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := IBCTransferEventDataStaticSize // Start dynamic data after static section

	// SourcePort (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// SourcePort (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.SourcePort)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.SourcePort))
	dynamicOffset += abi.Pad32(len(t.SourcePort))

	// SourceChannel (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// SourceChannel (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.SourceChannel)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.SourceChannel))
	dynamicOffset += abi.Pad32(len(t.SourceChannel))

	// Denom (offset)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(dynamicOffset))

	// Denom (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Denom)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Denom))
	dynamicOffset += abi.Pad32(len(t.Denom))

	// Amount (static)

	if err := abi.EncodeBigInt(t.Amount, buf[96:128], false); err != nil {
		return 0, err
	}

	// Memo (offset)
	binary.BigEndian.PutUint64(buf[128+24:128+32], uint64(dynamicOffset))

	// Memo (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Memo)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Memo))
	dynamicOffset += abi.Pad32(len(t.Memo))

	return dynamicOffset, nil
}

// Encode encodes IBCTransferEventData to ABI bytes
func (t IBCTransferEventData) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes IBCTransferEventData from ABI bytes in the provided buffer
func (t *IBCTransferEventData) Decode(data0 []byte) error {
	if len(data0) < IBCTransferEventDataStaticSize {
		return fmt.Errorf("insufficient data for IBCTransferEventData")
	}

	// SourcePort
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.SourcePort (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.SourcePort = string(data0[offset : offset+length])
	}
	// SourceChannel
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.SourceChannel (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.SourceChannel = string(data0[offset : offset+length])
	}
	// Denom
	{
		offset := int(binary.BigEndian.Uint64(data0[64+24 : 64+32]))

		// t.Denom (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Denom = string(data0[offset : offset+length])
	}
	// t.Amount (static)
	t.Amount = new(big.Int).SetBytes(data0[96:128])
	// Memo
	{
		offset := int(binary.BigEndian.Uint64(data0[128+24 : 128+32]))

		// t.Memo (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Memo = string(data0[offset : offset+length])
	}

	return nil
}
