// Code generated by go-abi. DO NOT EDIT.

package slashing

import (
	"encoding/binary"
	"fmt"

	cmn "github.com/cosmos/evm/precompiles/common"
	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// getParams()
	GetParamsSelector = [4]byte{0x5e, 0x61, 0x5a, 0x6b}
	// getSigningInfo(address)
	GetSigningInfoSelector = [4]byte{0x69, 0xe1, 0xf9, 0xdf}
	// getSigningInfos((bytes,uint64,uint64,bool,bool))
	GetSigningInfosSelector = [4]byte{0xc6, 0x91, 0x9f, 0x55}
	// unjail(address)
	UnjailSelector = [4]byte{0x44, 0x9e, 0xcf, 0xe6}
)

// Big endian integer versions of function selectors
const (
	GetParamsID       = 1583438443
	GetSigningInfoID  = 1776417247
	GetSigningInfosID = 3331432277
	UnjailID          = 1151258598
)

// Event signatures
var (
	// ValidatorUnjailed(address)
	ValidatorUnjailedEventTopic = common.Hash{0x93, 0x90, 0xb4, 0x53, 0x42, 0x65, 0x57, 0xda, 0x5e, 0xbd, 0xc3, 0x1f, 0x19, 0xa3, 0x77, 0x53, 0xca, 0x04, 0xad, 0xdf, 0x65, 0x6d, 0x32, 0xf3, 0x52, 0x32, 0x21, 0x1b, 0xb2, 0xaf, 0x3f, 0x19}
)

const PageRequestStaticSize = 160

// PageRequest represents an ABI tuple
type PageRequest struct {
	Key        []byte
	Offset     uint64
	Limit      uint64
	CountTotal bool
	Reverse    bool
}

// EncodedSize returns the total encoded size of PageRequest
func (t PageRequest) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Key)) // length + padded bytes data

	return PageRequestStaticSize + dynamicSize
}

// EncodeTo encodes PageRequest to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t PageRequest) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := PageRequestStaticSize // Start dynamic data after static section

	// Key (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Key (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Key)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], t.Key)
	dynamicOffset += abi.Pad32(len(t.Key))

	// Offset (static)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(t.Offset))
	// Limit (static)
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(t.Limit))
	// CountTotal (static)
	if t.CountTotal {
		buf[96+31] = 1
	}
	// Reverse (static)
	if t.Reverse {
		buf[128+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes PageRequest to ABI bytes
func (t PageRequest) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PageRequest from ABI bytes in the provided buffer
func (t *PageRequest) Decode(data0 []byte) error {
	if len(data0) < PageRequestStaticSize {
		return fmt.Errorf("insufficient data for PageRequest")
	}

	// Key
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Key (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// bytes data
		t.Key = data0[offset : offset+length]
	}
	// t.Offset (static)
	t.Offset = uint64(binary.BigEndian.Uint64(data0[32+24 : 32+32]))
	// t.Limit (static)
	t.Limit = uint64(binary.BigEndian.Uint64(data0[64+24 : 64+32]))
	// t.CountTotal (static)
	t.CountTotal = data0[96+31] == 1
	// t.Reverse (static)
	t.Reverse = data0[128+31] == 1

	return nil
}

const PageResponseStaticSize = 64

// PageResponse represents an ABI tuple
type PageResponse struct {
	NextKey []byte
	Total   uint64
}

// EncodedSize returns the total encoded size of PageResponse
func (t PageResponse) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.NextKey)) // length + padded bytes data

	return PageResponseStaticSize + dynamicSize
}

// EncodeTo encodes PageResponse to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t PageResponse) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := PageResponseStaticSize // Start dynamic data after static section

	// NextKey (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// NextKey (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.NextKey)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], t.NextKey)
	dynamicOffset += abi.Pad32(len(t.NextKey))

	// Total (static)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(t.Total))

	return dynamicOffset, nil
}

// Encode encodes PageResponse to ABI bytes
func (t PageResponse) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes PageResponse from ABI bytes in the provided buffer
func (t *PageResponse) Decode(data0 []byte) error {
	if len(data0) < PageResponseStaticSize {
		return fmt.Errorf("insufficient data for PageResponse")
	}

	// NextKey
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.NextKey (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// bytes data
		t.NextKey = data0[offset : offset+length]
	}
	// t.Total (static)
	t.Total = uint64(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

	return nil
}

const ParamsStaticSize = 256

// Params represents an ABI tuple
type Params struct {
	SignedBlocksWindow      int64
	MinSignedPerWindow      cmn.Dec
	DowntimeJailDuration    int64
	SlashFractionDoubleSign cmn.Dec
	SlashFractionDowntime   cmn.Dec
}

// EncodedSize returns the total encoded size of Params
func (t Params) EncodedSize() int {
	dynamicSize := 0

	return ParamsStaticSize + dynamicSize
}

// EncodeTo encodes Params to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Params) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := ParamsStaticSize // Start dynamic data after static section

	// SignedBlocksWindow (static)

	if t.SignedBlocksWindow < 0 {
		for i := 0; i < 24; i++ {
			buf[0+i] = 0xff
		}
	}
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(t.SignedBlocksWindow))

	// MinSignedPerWindow (static)
	// Encode nested tuple t.MinSignedPerWindow
	if _, err := t.MinSignedPerWindow.EncodeTo(buf[32:]); err != nil {
		return 0, err
	}

	// DowntimeJailDuration (static)

	if t.DowntimeJailDuration < 0 {
		for i := 0; i < 24; i++ {
			buf[96+i] = 0xff
		}
	}
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(t.DowntimeJailDuration))

	// SlashFractionDoubleSign (static)
	// Encode nested tuple t.SlashFractionDoubleSign
	if _, err := t.SlashFractionDoubleSign.EncodeTo(buf[128:]); err != nil {
		return 0, err
	}

	// SlashFractionDowntime (static)
	// Encode nested tuple t.SlashFractionDowntime
	if _, err := t.SlashFractionDowntime.EncodeTo(buf[192:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes Params to ABI bytes
func (t Params) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Params from ABI bytes in the provided buffer
func (t *Params) Decode(data0 []byte) error {
	if len(data0) < ParamsStaticSize {
		return fmt.Errorf("insufficient data for Params")
	}

	// t.SignedBlocksWindow (static)
	t.SignedBlocksWindow = int64(binary.BigEndian.Uint64(data0[0+24 : 0+32]))
	// t.MinSignedPerWindow (static)
	if err := t.MinSignedPerWindow.Decode(data0[32:96]); err != nil {
		return err
	}
	// t.DowntimeJailDuration (static)
	t.DowntimeJailDuration = int64(binary.BigEndian.Uint64(data0[96+24 : 96+32]))
	// t.SlashFractionDoubleSign (static)
	if err := t.SlashFractionDoubleSign.Decode(data0[128:192]); err != nil {
		return err
	}
	// t.SlashFractionDowntime (static)
	if err := t.SlashFractionDowntime.Decode(data0[192:256]); err != nil {
		return err
	}

	return nil
}

const SigningInfoStaticSize = 192

// SigningInfo represents an ABI tuple
type SigningInfo struct {
	ValidatorAddress    common.Address
	StartHeight         int64
	IndexOffset         int64
	JailedUntil         int64
	Tombstoned          bool
	MissedBlocksCounter int64
}

// EncodedSize returns the total encoded size of SigningInfo
func (t SigningInfo) EncodedSize() int {
	dynamicSize := 0

	return SigningInfoStaticSize + dynamicSize
}

// EncodeTo encodes SigningInfo to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t SigningInfo) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := SigningInfoStaticSize // Start dynamic data after static section

	// ValidatorAddress (static)
	copy(buf[0+12:0+32], t.ValidatorAddress[:])
	// StartHeight (static)

	if t.StartHeight < 0 {
		for i := 0; i < 24; i++ {
			buf[32+i] = 0xff
		}
	}
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(t.StartHeight))

	// IndexOffset (static)

	if t.IndexOffset < 0 {
		for i := 0; i < 24; i++ {
			buf[64+i] = 0xff
		}
	}
	binary.BigEndian.PutUint64(buf[64+24:64+32], uint64(t.IndexOffset))

	// JailedUntil (static)

	if t.JailedUntil < 0 {
		for i := 0; i < 24; i++ {
			buf[96+i] = 0xff
		}
	}
	binary.BigEndian.PutUint64(buf[96+24:96+32], uint64(t.JailedUntil))

	// Tombstoned (static)
	if t.Tombstoned {
		buf[128+31] = 1
	}
	// MissedBlocksCounter (static)

	if t.MissedBlocksCounter < 0 {
		for i := 0; i < 24; i++ {
			buf[160+i] = 0xff
		}
	}
	binary.BigEndian.PutUint64(buf[160+24:160+32], uint64(t.MissedBlocksCounter))

	return dynamicOffset, nil
}

// Encode encodes SigningInfo to ABI bytes
func (t SigningInfo) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes SigningInfo from ABI bytes in the provided buffer
func (t *SigningInfo) Decode(data0 []byte) error {
	if len(data0) < SigningInfoStaticSize {
		return fmt.Errorf("insufficient data for SigningInfo")
	}

	// t.ValidatorAddress (static)
	copy(t.ValidatorAddress[:], data0[0+12:0+32])
	// t.StartHeight (static)
	t.StartHeight = int64(binary.BigEndian.Uint64(data0[32+24 : 32+32]))
	// t.IndexOffset (static)
	t.IndexOffset = int64(binary.BigEndian.Uint64(data0[64+24 : 64+32]))
	// t.JailedUntil (static)
	t.JailedUntil = int64(binary.BigEndian.Uint64(data0[96+24 : 96+32]))
	// t.Tombstoned (static)
	t.Tombstoned = data0[128+31] == 1
	// t.MissedBlocksCounter (static)
	t.MissedBlocksCounter = int64(binary.BigEndian.Uint64(data0[160+24 : 160+32]))

	return nil
}

const GetParamsReturnStaticSize = 256

// GetParamsReturn represents an ABI tuple
type GetParamsReturn struct {
	Params Params
}

// EncodedSize returns the total encoded size of GetParamsReturn
func (t GetParamsReturn) EncodedSize() int {
	dynamicSize := 0

	return GetParamsReturnStaticSize + dynamicSize
}

// EncodeTo encodes GetParamsReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t GetParamsReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := GetParamsReturnStaticSize // Start dynamic data after static section

	// Params (static)
	// Encode nested tuple t.Params
	if _, err := t.Params.EncodeTo(buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes GetParamsReturn to ABI bytes
func (t GetParamsReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetParamsReturn from ABI bytes in the provided buffer
func (t *GetParamsReturn) Decode(data0 []byte) error {
	if len(data0) < GetParamsReturnStaticSize {
		return fmt.Errorf("insufficient data for GetParamsReturn")
	}

	// t.Params (static)
	if err := t.Params.Decode(data0[0:256]); err != nil {
		return err
	}

	return nil
}

const GetSigningInfoCallStaticSize = 32

// GetSigningInfoCall represents an ABI tuple
type GetSigningInfoCall struct {
	ConsAddress common.Address
}

// EncodedSize returns the total encoded size of GetSigningInfoCall
func (t GetSigningInfoCall) EncodedSize() int {
	dynamicSize := 0

	return GetSigningInfoCallStaticSize + dynamicSize
}

// EncodeTo encodes GetSigningInfoCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t GetSigningInfoCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := GetSigningInfoCallStaticSize // Start dynamic data after static section

	// ConsAddress (static)
	copy(buf[0+12:0+32], t.ConsAddress[:])

	return dynamicOffset, nil
}

// Encode encodes GetSigningInfoCall to ABI bytes
func (t GetSigningInfoCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetSigningInfoCall from ABI bytes in the provided buffer
func (t *GetSigningInfoCall) Decode(data0 []byte) error {
	if len(data0) < GetSigningInfoCallStaticSize {
		return fmt.Errorf("insufficient data for GetSigningInfoCall")
	}

	// t.ConsAddress (static)
	copy(t.ConsAddress[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes getSigningInfo arguments to ABI bytes including function selector
func (t GetSigningInfoCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], GetSigningInfoSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const GetSigningInfoReturnStaticSize = 192

// GetSigningInfoReturn represents an ABI tuple
type GetSigningInfoReturn struct {
	SigningInfo SigningInfo
}

// EncodedSize returns the total encoded size of GetSigningInfoReturn
func (t GetSigningInfoReturn) EncodedSize() int {
	dynamicSize := 0

	return GetSigningInfoReturnStaticSize + dynamicSize
}

// EncodeTo encodes GetSigningInfoReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t GetSigningInfoReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := GetSigningInfoReturnStaticSize // Start dynamic data after static section

	// SigningInfo (static)
	// Encode nested tuple t.SigningInfo
	if _, err := t.SigningInfo.EncodeTo(buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes GetSigningInfoReturn to ABI bytes
func (t GetSigningInfoReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetSigningInfoReturn from ABI bytes in the provided buffer
func (t *GetSigningInfoReturn) Decode(data0 []byte) error {
	if len(data0) < GetSigningInfoReturnStaticSize {
		return fmt.Errorf("insufficient data for GetSigningInfoReturn")
	}

	// t.SigningInfo (static)
	if err := t.SigningInfo.Decode(data0[0:192]); err != nil {
		return err
	}

	return nil
}

const GetSigningInfosCallStaticSize = 32

// GetSigningInfosCall represents an ABI tuple
type GetSigningInfosCall struct {
	Pagination PageRequest
}

// EncodedSize returns the total encoded size of GetSigningInfosCall
func (t GetSigningInfosCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += t.Pagination.EncodedSize() // dynamic tuple

	return GetSigningInfosCallStaticSize + dynamicSize
}

// EncodeTo encodes GetSigningInfosCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t GetSigningInfosCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := GetSigningInfosCallStaticSize // Start dynamic data after static section

	// Pagination (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Pagination (dynamic)
	{
		n, err := t.Pagination.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes GetSigningInfosCall to ABI bytes
func (t GetSigningInfosCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetSigningInfosCall from ABI bytes in the provided buffer
func (t *GetSigningInfosCall) Decode(data0 []byte) error {
	if len(data0) < GetSigningInfosCallStaticSize {
		return fmt.Errorf("insufficient data for GetSigningInfosCall")
	}

	// Pagination
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Pagination (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.Pagination")
		}
		if err := t.Pagination.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

// EncodeWithSelector encodes getSigningInfos arguments to ABI bytes including function selector
func (t GetSigningInfosCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], GetSigningInfosSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const GetSigningInfosReturnStaticSize = 64

// GetSigningInfosReturn represents an ABI tuple
type GetSigningInfosReturn struct {
	SigningInfos []SigningInfo
	PageResponse PageResponse
}

// EncodedSize returns the total encoded size of GetSigningInfosReturn
func (t GetSigningInfosReturn) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + 192*len(t.SigningInfos) // length + static elements
	dynamicSize += t.PageResponse.EncodedSize() // dynamic tuple

	return GetSigningInfosReturnStaticSize + dynamicSize
}

// EncodeTo encodes GetSigningInfosReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t GetSigningInfosReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := GetSigningInfosReturnStaticSize // Start dynamic data after static section

	// SigningInfos (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// SigningInfos (dynamic)
	{
		// length
		binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.SigningInfos)))
		dynamicOffset += 32

		// data without dynamic region
		buf := buf[dynamicOffset:]
		var offset int
		for _, item := range t.SigningInfos {
			tmpBuf := buf[offset:]

			// Encode nested tuple item
			if _, err := item.EncodeTo(tmpBuf[0:]); err != nil {
				return 0, err
			}

			offset += 192
		}
		dynamicOffset += offset

	}

	// PageResponse (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// PageResponse (dynamic)
	{
		n, err := t.PageResponse.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	return dynamicOffset, nil
}

// Encode encodes GetSigningInfosReturn to ABI bytes
func (t GetSigningInfosReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetSigningInfosReturn from ABI bytes in the provided buffer
func (t *GetSigningInfosReturn) Decode(data0 []byte) error {
	if len(data0) < GetSigningInfosReturnStaticSize {
		return fmt.Errorf("insufficient data for GetSigningInfosReturn")
	}

	// SigningInfos
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.SigningInfos (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// slice data
		t.SigningInfos = make([]SigningInfo, length)
		data1 := data0[offset:]

		offset = 0
		for i0 := 0; i0 < length; i0++ {
			// t.SigningInfos[i0] (static)
			if err := t.SigningInfos[i0].Decode(data1[offset : offset+192]); err != nil {
				return err
			}
			offset += 192
		}
	}
	// PageResponse
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.PageResponse (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.PageResponse")
		}
		if err := t.PageResponse.Decode(data0[offset:]); err != nil {
			return err
		}
	}

	return nil
}

const UnjailCallStaticSize = 32

// UnjailCall represents an ABI tuple
type UnjailCall struct {
	ValidatorAddress common.Address
}

// EncodedSize returns the total encoded size of UnjailCall
func (t UnjailCall) EncodedSize() int {
	dynamicSize := 0

	return UnjailCallStaticSize + dynamicSize
}

// EncodeTo encodes UnjailCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t UnjailCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := UnjailCallStaticSize // Start dynamic data after static section

	// ValidatorAddress (static)
	copy(buf[0+12:0+32], t.ValidatorAddress[:])

	return dynamicOffset, nil
}

// Encode encodes UnjailCall to ABI bytes
func (t UnjailCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes UnjailCall from ABI bytes in the provided buffer
func (t *UnjailCall) Decode(data0 []byte) error {
	if len(data0) < UnjailCallStaticSize {
		return fmt.Errorf("insufficient data for UnjailCall")
	}

	// t.ValidatorAddress (static)
	copy(t.ValidatorAddress[:], data0[0+12:0+32])

	return nil
}

// EncodeWithSelector encodes unjail arguments to ABI bytes including function selector
func (t UnjailCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], UnjailSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const UnjailReturnStaticSize = 32

// UnjailReturn represents an ABI tuple
type UnjailReturn struct {
	Success bool
}

// EncodedSize returns the total encoded size of UnjailReturn
func (t UnjailReturn) EncodedSize() int {
	dynamicSize := 0

	return UnjailReturnStaticSize + dynamicSize
}

// EncodeTo encodes UnjailReturn to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t UnjailReturn) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := UnjailReturnStaticSize // Start dynamic data after static section

	// Success (static)
	if t.Success {
		buf[0+31] = 1
	}

	return dynamicOffset, nil
}

// Encode encodes UnjailReturn to ABI bytes
func (t UnjailReturn) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes UnjailReturn from ABI bytes in the provided buffer
func (t *UnjailReturn) Decode(data0 []byte) error {
	if len(data0) < UnjailReturnStaticSize {
		return fmt.Errorf("insufficient data for UnjailReturn")
	}

	// t.Success (static)
	t.Success = data0[0+31] == 1

	return nil
}

// ValidatorUnjailedEvent represents an ABI event
type ValidatorUnjailedEvent struct {
	ValidatorUnjailedEventIndexed
	ValidatorUnjailedEventData
}

// NewValidatorUnjailedEvent constructs a new ValidatorUnjailed event
func NewValidatorUnjailedEvent(
	validator common.Address,
) ValidatorUnjailedEvent {
	return ValidatorUnjailedEvent{
		ValidatorUnjailedEventIndexed: ValidatorUnjailedEventIndexed{
			Validator: validator,
		},
		ValidatorUnjailedEventData: ValidatorUnjailedEventData{},
	}
}

// ValidatorUnjailed represents an ABI event
type ValidatorUnjailedEventIndexed struct {
	Validator common.Address
}

// EncodeTopics encodes indexed fields of ValidatorUnjailed event to topics
func (e ValidatorUnjailedEventIndexed) EncodeTopics() []common.Hash {
	topics := make([]common.Hash, 0, 2)
	topics = append(topics, ValidatorUnjailedEventTopic)

	// Encode indexed field Validator
	{
		var buf common.Hash

		// Validator (static)
		copy(buf[0+12:0+32], e.Validator[:])

		topics = append(topics, buf)
	}

	return topics
}

// DecodeTopics decodes indexed fields of ValidatorUnjailed event from topics
func (e *ValidatorUnjailedEventIndexed) DecodeTopics(topics []common.Hash) error {
	if len(topics) < 2 {
		return fmt.Errorf("insufficient topics for ValidatorUnjailed event")
	}

	// Check event signature
	if topics[0] != ValidatorUnjailedEventTopic {
		return fmt.Errorf("invalid event signature for ValidatorUnjailed event")
	}

	// Validator (static)
	{
		data := topics[1][:]
		offset := 0

		// e.Validator (static)
		copy(e.Validator[:], data[offset+12:offset+32])

	}

	return nil
}

type ValidatorUnjailedEventData abi.EmptyTuple
