// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/precisebank/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the precisebank module's genesis state.
type GenesisState struct {
	// balances is a list of all the balances in the precisebank module.
	Balances FractionalBalances `protobuf:"bytes,1,rep,name=balances,proto3,castrepeated=FractionalBalances" json:"balances"`
	// remainder is an internal value of how much extra fractional digits are
	// still backed by the reserve, but not assigned to any account.
	Remainder cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=remainder,proto3,customtype=cosmossdk.io/math.Int" json:"remainder"`
	// coin_info is the coin info for the precisebank module.
	CoinInfo CoinInfo `protobuf:"bytes,3,opt,name=coin_info,json=coinInfo,proto3" json:"coin_info"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e59d417e91f4d8e9, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetBalances() FractionalBalances {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *GenesisState) GetCoinInfo() CoinInfo {
	if m != nil {
		return m.CoinInfo
	}
	return CoinInfo{}
}

// FractionalBalance defines the fractional portion of an account balance
type FractionalBalance struct {
	// address is the address of the balance holder.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// amount indicates amount of only the fractional balance owned by the
	// address. FractionalBalance currently only supports tracking 1 single asset,
	// e.g. fractional balances of uatom.
	Amount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
}

func (m *FractionalBalance) Reset()         { *m = FractionalBalance{} }
func (m *FractionalBalance) String() string { return proto.CompactTextString(m) }
func (*FractionalBalance) ProtoMessage()    {}
func (*FractionalBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_e59d417e91f4d8e9, []int{1}
}
func (m *FractionalBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FractionalBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FractionalBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FractionalBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FractionalBalance.Merge(m, src)
}
func (m *FractionalBalance) XXX_Size() int {
	return m.Size()
}
func (m *FractionalBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_FractionalBalance.DiscardUnknown(m)
}

var xxx_messageInfo_FractionalBalance proto.InternalMessageInfo

// CoinInfo holds parameters for the precisebank module.
type CoinInfo struct {
	// integer_coin_denom is the base asset of the precisebank module.
	IntegerCoinDenom string `protobuf:"bytes,1,opt,name=integer_coin_denom,json=integerCoinDenom,proto3" json:"integer_coin_denom,omitempty"`
	// extended_coin_denom is the extended asset of the precisebank module.
	ExtendedCoinDenom string `protobuf:"bytes,2,opt,name=extended_coin_denom,json=extendedCoinDenom,proto3" json:"extended_coin_denom,omitempty"`
	// conversion_factor is the number of fractional digits to convert to the
	// base asset.
	ConversionFactor cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=conversion_factor,json=conversionFactor,proto3,customtype=cosmossdk.io/math.Int" json:"conversion_factor"`
}

func (m *CoinInfo) Reset()         { *m = CoinInfo{} }
func (m *CoinInfo) String() string { return proto.CompactTextString(m) }
func (*CoinInfo) ProtoMessage()    {}
func (*CoinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e59d417e91f4d8e9, []int{2}
}
func (m *CoinInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinInfo.Merge(m, src)
}
func (m *CoinInfo) XXX_Size() int {
	return m.Size()
}
func (m *CoinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CoinInfo proto.InternalMessageInfo

func (m *CoinInfo) GetIntegerCoinDenom() string {
	if m != nil {
		return m.IntegerCoinDenom
	}
	return ""
}

func (m *CoinInfo) GetExtendedCoinDenom() string {
	if m != nil {
		return m.ExtendedCoinDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.evm.precisebank.v1.GenesisState")
	proto.RegisterType((*FractionalBalance)(nil), "cosmos.evm.precisebank.v1.FractionalBalance")
	proto.RegisterType((*CoinInfo)(nil), "cosmos.evm.precisebank.v1.CoinInfo")
}

func init() {
	proto.RegisterFile("cosmos/evm/precisebank/v1/genesis.proto", fileDescriptor_e59d417e91f4d8e9)
}

var fileDescriptor_e59d417e91f4d8e9 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x3f, 0x6f, 0xd3, 0x40,
	0x14, 0xb7, 0x5b, 0x54, 0xd2, 0x2b, 0x43, 0x73, 0x14, 0x29, 0x64, 0xb0, 0xa3, 0x30, 0x10, 0xa0,
	0x3d, 0xab, 0x61, 0xeb, 0x46, 0x82, 0x82, 0xb2, 0xba, 0x0b, 0x62, 0x89, 0x2e, 0xf6, 0x8b, 0x7b,
	0x6a, 0xfd, 0x5e, 0x74, 0x77, 0x8d, 0xca, 0x27, 0x00, 0x31, 0x31, 0x31, 0x77, 0x66, 0x62, 0xe8,
	0x87, 0xe8, 0x58, 0x75, 0x42, 0x0c, 0x05, 0x25, 0x03, 0x7c, 0x0c, 0xe4, 0x3f, 0x69, 0x52, 0x55,
	0x20, 0xc1, 0x62, 0xf9, 0xde, 0xef, 0xcf, 0xfb, 0xbd, 0xf3, 0x33, 0x7b, 0x1c, 0x91, 0x49, 0xc9,
	0x04, 0x30, 0x49, 0x83, 0xb1, 0x86, 0x48, 0x19, 0x18, 0x4a, 0x3c, 0x0c, 0x26, 0xbb, 0x41, 0x02,
	0x08, 0x46, 0x19, 0x31, 0xd6, 0x64, 0x89, 0x3f, 0x2c, 0x88, 0x02, 0x26, 0xa9, 0x58, 0x22, 0x8a,
	0xc9, 0x6e, 0xbd, 0x84, 0x06, 0x39, 0x31, 0x28, 0x79, 0xf9, 0xa1, 0xbe, 0x95, 0x50, 0x42, 0x45,
	0x3d, 0x7b, 0x2b, 0xab, 0x55, 0x99, 0x2a, 0xa4, 0x20, 0x7f, 0x16, 0xa5, 0xe6, 0xbb, 0x15, 0x76,
	0xef, 0x55, 0xd1, 0x70, 0xdf, 0x4a, 0x0b, 0x3c, 0x66, 0x95, 0xa1, 0x3c, 0x92, 0x18, 0x81, 0xa9,
	0xb9, 0x8d, 0xd5, 0xd6, 0x46, 0x7b, 0x5b, 0xfc, 0x31, 0x82, 0xe8, 0x69, 0x19, 0x59, 0x45, 0x28,
	0x8f, 0x3a, 0x85, 0xa8, 0x53, 0x3f, 0xbf, 0xf2, 0x9d, 0xcf, 0xdf, 0x7d, 0x7e, 0x0b, 0x32, 0xe1,
	0xb5, 0x33, 0xef, 0xb3, 0x75, 0x0d, 0xa9, 0x54, 0x18, 0x83, 0xae, 0xad, 0x34, 0xdc, 0xd6, 0x7a,
	0xe7, 0x59, 0x26, 0xfc, 0x76, 0xe5, 0x3f, 0x28, 0xba, 0x99, 0xf8, 0x50, 0x28, 0x0a, 0x52, 0x69,
	0x0f, 0x44, 0x1f, 0xed, 0xe5, 0xd9, 0x0e, 0x2b, 0x63, 0xf4, 0xd1, 0x86, 0x0b, 0x35, 0xef, 0xb1,
	0xf5, 0x88, 0x14, 0x0e, 0x14, 0x8e, 0xa8, 0xb6, 0xda, 0x70, 0x5b, 0x1b, 0xed, 0x47, 0x7f, 0x49,
	0xdc, 0x25, 0x85, 0x7d, 0x1c, 0x51, 0xe7, 0x4e, 0xd6, 0x2f, 0xac, 0x44, 0xe5, 0xb9, 0xf9, 0xc9,
	0x65, 0xd5, 0x5b, 0x99, 0x79, 0x9b, 0xdd, 0x95, 0x71, 0xac, 0xc1, 0x64, 0xb7, 0x91, 0xc5, 0xac,
	0x5d, 0x9e, 0xed, 0x6c, 0x95, 0xf6, 0x2f, 0x0a, 0x64, 0xdf, 0x6a, 0x85, 0x49, 0x38, 0x27, 0xf2,
	0x2e, 0x5b, 0x93, 0x29, 0x1d, 0xa3, 0xfd, 0x9f, 0xc9, 0x4a, 0xe9, 0x5e, 0xe5, 0xfd, 0xa9, 0xef,
	0xfc, 0x3a, 0xf5, 0x9d, 0xe6, 0xcc, 0x65, 0x95, 0x79, 0x6a, 0xbe, 0xcd, 0xb8, 0x42, 0x0b, 0x09,
	0xe8, 0x41, 0x3e, 0x75, 0x0c, 0x48, 0x69, 0x11, 0x2d, 0xdc, 0x2c, 0x91, 0x8c, 0xfc, 0x32, 0xab,
	0x73, 0xc1, 0xee, 0xc3, 0x89, 0x05, 0x8c, 0x21, 0x5e, 0xa6, 0xe7, 0xb1, 0xc2, 0xea, 0x1c, 0x5a,
	0xf0, 0x5f, 0xb3, 0x6a, 0x44, 0x38, 0x01, 0x6d, 0x14, 0xe1, 0x60, 0x24, 0x23, 0x4b, 0x3a, 0xbf,
	0xd3, 0x7f, 0x1c, 0x62, 0x73, 0xe1, 0xd2, 0xcb, 0x4d, 0xf6, 0xfc, 0x0f, 0x3f, 0xbf, 0x3c, 0xad,
	0x67, 0xdb, 0x7e, 0x72, 0x63, 0xdf, 0xaf, 0x3f, 0x47, 0xf7, 0x7c, 0xea, 0xb9, 0x17, 0x53, 0xcf,
	0xfd, 0x31, 0xf5, 0xdc, 0x8f, 0x33, 0xcf, 0xb9, 0x98, 0x79, 0xce, 0xd7, 0x99, 0xe7, 0xbc, 0x79,
	0x92, 0x28, 0x7b, 0x70, 0x3c, 0x14, 0x11, 0xa5, 0xc1, 0xd2, 0x5f, 0x73, 0xd3, 0xc7, 0xbe, 0x1d,
	0x83, 0x19, 0xae, 0xe5, 0x4b, 0xfd, 0xfc, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x14, 0x5d,
	0xfd, 0x5e, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.CoinInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Remainder.Size()
		i -= size
		if _, err := m.Remainder.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Balances) > 0 {
		for iNdEx := len(m.Balances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *FractionalBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FractionalBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FractionalBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CoinInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ConversionFactor.Size()
		i -= size
		if _, err := m.ConversionFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ExtendedCoinDenom) > 0 {
		i -= len(m.ExtendedCoinDenom)
		copy(dAtA[i:], m.ExtendedCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ExtendedCoinDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IntegerCoinDenom) > 0 {
		i -= len(m.IntegerCoinDenom)
		copy(dAtA[i:], m.IntegerCoinDenom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.IntegerCoinDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Balances) > 0 {
		for _, e := range m.Balances {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Remainder.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.CoinInfo.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *FractionalBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *CoinInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IntegerCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ExtendedCoinDenom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.ConversionFactor.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balances = append(m.Balances, FractionalBalance{})
			if err := m.Balances[len(m.Balances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remainder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Remainder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CoinInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CoinInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FractionalBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FractionalBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FractionalBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CoinInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IntegerCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IntegerCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtendedCoinDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExtendedCoinDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConversionFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConversionFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
