// Code generated by go-abi. DO NOT EDIT.

package counter

import (
	"io"
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// add()
	AddSelector = [4]byte{0x4f, 0x2b, 0xe9, 0x1f}
	// getCounter()
	GetCounterSelector = [4]byte{0x8a, 0xda, 0x06, 0x6e}
	// subtract()
	SubtractSelector = [4]byte{0x6d, 0xee, 0xba, 0xe3}
)

// Big endian integer versions of function selectors
const (
	AddID        = 1328277791
	GetCounterID = 2329544302
	SubtractID   = 1844361955
)

var _ abi.Method = (*AddCall)(nil)

// AddCall represents the input arguments for add function
type AddCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t AddCall) GetMethodName() string {
	return "add"
}

// GetMethodID returns the function name
func (t AddCall) GetMethodID() uint32 {
	return AddID
}

// GetMethodSelector returns the function name
func (t AddCall) GetMethodSelector() [4]byte {
	return AddSelector
}

// EncodeWithSelector encodes add arguments to ABI bytes including function selector
func (t AddCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], AddSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// AddReturn represents the input arguments for add function
type AddReturn struct {
	abi.EmptyTuple
}

var _ abi.Method = (*GetCounterCall)(nil)

// GetCounterCall represents the input arguments for getCounter function
type GetCounterCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t GetCounterCall) GetMethodName() string {
	return "getCounter"
}

// GetMethodID returns the function name
func (t GetCounterCall) GetMethodID() uint32 {
	return GetCounterID
}

// GetMethodSelector returns the function name
func (t GetCounterCall) GetMethodSelector() [4]byte {
	return GetCounterSelector
}

// EncodeWithSelector encodes getCounter arguments to ABI bytes including function selector
func (t GetCounterCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], GetCounterSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

const GetCounterReturnStaticSize = 32

var _ abi.Tuple = (*GetCounterReturn)(nil)

// GetCounterReturn represents an ABI tuple
type GetCounterReturn struct {
	Field1 *big.Int
}

// EncodedSize returns the total encoded size of GetCounterReturn
func (t GetCounterReturn) EncodedSize() int {
	dynamicSize := 0

	return GetCounterReturnStaticSize + dynamicSize
}

// EncodeTo encodes GetCounterReturn to ABI bytes in the provided buffer
func (value GetCounterReturn) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := GetCounterReturnStaticSize // Start dynamic data after static section
	// Field Field1: uint256
	if _, err := abi.EncodeUint256(value.Field1, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes GetCounterReturn to ABI bytes
func (value GetCounterReturn) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes GetCounterReturn from ABI bytes in the provided buffer
func (t *GetCounterReturn) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Field1: uint256
	t.Field1, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

var _ abi.Method = (*SubtractCall)(nil)

// SubtractCall represents the input arguments for subtract function
type SubtractCall struct {
	abi.EmptyTuple
}

// GetMethodName returns the function name
func (t SubtractCall) GetMethodName() string {
	return "subtract"
}

// GetMethodID returns the function name
func (t SubtractCall) GetMethodID() uint32 {
	return SubtractID
}

// GetMethodSelector returns the function name
func (t SubtractCall) GetMethodSelector() [4]byte {
	return SubtractSelector
}

// EncodeWithSelector encodes subtract arguments to ABI bytes including function selector
func (t SubtractCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], SubtractSelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}

// SubtractReturn represents the input arguments for subtract function
type SubtractReturn struct {
	abi.EmptyTuple
}

// Event signatures
var (
	// Added(uint256)
	AddedEventTopic = common.Hash{0x64, 0xa5, 0x50, 0x44, 0xd1, 0xf2, 0xed, 0xde, 0xbe, 0x1b, 0x90, 0xe8, 0xe2, 0x85, 0x3e, 0x8e, 0x96, 0x93, 0x1c, 0xef, 0xad, 0xbf, 0xa0, 0xb2, 0xce, 0xb3, 0x4b, 0xee, 0x36, 0x06, 0x19, 0x41}
	// Changed(uint256)
	ChangedEventTopic = common.Hash{0x93, 0x8d, 0x2e, 0xe5, 0xbe, 0x9c, 0xfb, 0x0f, 0x72, 0x70, 0xee, 0x2e, 0xff, 0x90, 0x50, 0x7e, 0x94, 0xb3, 0x76, 0x25, 0xd9, 0xd2, 0xb3, 0xa6, 0x1c, 0x97, 0xd3, 0x0a, 0x45, 0x60, 0xb8, 0x29}
)

// AddedEvent represents the Added event
var _ abi.Event = (*AddedEvent)(nil)

type AddedEvent struct {
	AddedEventIndexed
	AddedEventData
}

// NewAddedEvent constructs a new Added event
func NewAddedEvent(
	counter *big.Int,
) AddedEvent {
	return AddedEvent{
		AddedEventIndexed: AddedEventIndexed{},
		AddedEventData: AddedEventData{
			Counter: counter,
		},
	}
}

// GetEventName returns the event name
func (e AddedEvent) GetEventName() string {
	return "Added"
}

// GetEventID returns the event ID (topic)
func (e AddedEvent) GetEventID() common.Hash {
	return AddedEventTopic
}

type AddedEventIndexed struct {
	abi.EmptyIndexed
}

const AddedEventDataStaticSize = 32

var _ abi.Tuple = (*AddedEventData)(nil)

// AddedEventData represents an ABI tuple
type AddedEventData struct {
	Counter *big.Int
}

// EncodedSize returns the total encoded size of AddedEventData
func (t AddedEventData) EncodedSize() int {
	dynamicSize := 0

	return AddedEventDataStaticSize + dynamicSize
}

// EncodeTo encodes AddedEventData to ABI bytes in the provided buffer
func (value AddedEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := AddedEventDataStaticSize // Start dynamic data after static section
	// Field Counter: uint256
	if _, err := abi.EncodeUint256(value.Counter, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes AddedEventData to ABI bytes
func (value AddedEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes AddedEventData from ABI bytes in the provided buffer
func (t *AddedEventData) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Counter: uint256
	t.Counter, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}

// ChangedEvent represents the Changed event
var _ abi.Event = (*ChangedEvent)(nil)

type ChangedEvent struct {
	ChangedEventIndexed
	ChangedEventData
}

// NewChangedEvent constructs a new Changed event
func NewChangedEvent(
	counter *big.Int,
) ChangedEvent {
	return ChangedEvent{
		ChangedEventIndexed: ChangedEventIndexed{},
		ChangedEventData: ChangedEventData{
			Counter: counter,
		},
	}
}

// GetEventName returns the event name
func (e ChangedEvent) GetEventName() string {
	return "Changed"
}

// GetEventID returns the event ID (topic)
func (e ChangedEvent) GetEventID() common.Hash {
	return ChangedEventTopic
}

type ChangedEventIndexed struct {
	abi.EmptyIndexed
}

const ChangedEventDataStaticSize = 32

var _ abi.Tuple = (*ChangedEventData)(nil)

// ChangedEventData represents an ABI tuple
type ChangedEventData struct {
	Counter *big.Int
}

// EncodedSize returns the total encoded size of ChangedEventData
func (t ChangedEventData) EncodedSize() int {
	dynamicSize := 0

	return ChangedEventDataStaticSize + dynamicSize
}

// EncodeTo encodes ChangedEventData to ABI bytes in the provided buffer
func (value ChangedEventData) EncodeTo(buf []byte) (int, error) {
	// Encode tuple fields
	dynamicOffset := ChangedEventDataStaticSize // Start dynamic data after static section
	// Field Counter: uint256
	if _, err := abi.EncodeUint256(value.Counter, buf[0:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes ChangedEventData to ABI bytes
func (value ChangedEventData) Encode() ([]byte, error) {
	buf := make([]byte, value.EncodedSize())
	if _, err := value.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes ChangedEventData from ABI bytes in the provided buffer
func (t *ChangedEventData) Decode(data []byte) (int, error) {
	if len(data) < 32 {
		return 0, io.ErrUnexpectedEOF
	}
	var (
		err error
	)
	dynamicOffset := 32
	// Decode static field Counter: uint256
	t.Counter, _, err = abi.DecodeUint256(data[0:])
	if err != nil {
		return 0, err
	}
	return dynamicOffset, nil
}
