// Code generated by go-abi. DO NOT EDIT.

package common

import (
	"encoding/binary"
	"fmt"
	"math/big"

	"github.com/yihuang/go-abi"
)

// Function selectors
var (
	// dummy((string,uint256),(string,uint256,uint8),(uint256,uint8))
	DummySelector = [4]byte{0x83, 0x6f, 0xaf, 0x55}
)

// Big endian integer versions of function selectors
const (
	DummyID = 2205134677
)

const CoinStaticSize = 64

// Coin represents an ABI tuple
type Coin struct {
	Denom  string
	Amount *big.Int
}

// EncodedSize returns the total encoded size of Coin
func (t Coin) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Denom)) // length + padded string data

	return CoinStaticSize + dynamicSize
}

// EncodeTo encodes Coin to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Coin) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := CoinStaticSize // Start dynamic data after static section

	// Denom (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Denom (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Denom)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Denom))
	dynamicOffset += abi.Pad32(len(t.Denom))

	// Amount (static)

	if err := abi.EncodeBigInt(t.Amount, buf[32:64], false); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes Coin to ABI bytes
func (t Coin) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Coin from ABI bytes in the provided buffer
func (t *Coin) Decode(data0 []byte) error {
	if len(data0) < CoinStaticSize {
		return fmt.Errorf("insufficient data for Coin")
	}

	// Denom
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Denom (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Denom = string(data0[offset : offset+length])
	}
	// t.Amount (static)
	t.Amount = new(big.Int).SetBytes(data0[32:64])

	return nil
}

const DecStaticSize = 64

// Dec represents an ABI tuple
type Dec struct {
	Value     *big.Int
	Precision uint8
}

// EncodedSize returns the total encoded size of Dec
func (t Dec) EncodedSize() int {
	dynamicSize := 0

	return DecStaticSize + dynamicSize
}

// EncodeTo encodes Dec to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t Dec) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DecStaticSize // Start dynamic data after static section

	// Value (static)

	if err := abi.EncodeBigInt(t.Value, buf[0:32], false); err != nil {
		return 0, err
	}

	// Precision (static)
	buf[32+31] = byte(t.Precision)

	return dynamicOffset, nil
}

// Encode encodes Dec to ABI bytes
func (t Dec) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes Dec from ABI bytes in the provided buffer
func (t *Dec) Decode(data0 []byte) error {
	if len(data0) < DecStaticSize {
		return fmt.Errorf("insufficient data for Dec")
	}

	// t.Value (static)
	t.Value = new(big.Int).SetBytes(data0[0:32])
	// t.Precision (static)
	t.Precision = uint8(data0[32+31])

	return nil
}

const DecCoinStaticSize = 96

// DecCoin represents an ABI tuple
type DecCoin struct {
	Denom     string
	Amount    *big.Int
	Precision uint8
}

// EncodedSize returns the total encoded size of DecCoin
func (t DecCoin) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += 32 + abi.Pad32(len(t.Denom)) // length + padded string data

	return DecCoinStaticSize + dynamicSize
}

// EncodeTo encodes DecCoin to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DecCoin) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DecCoinStaticSize // Start dynamic data after static section

	// Denom (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// Denom (dynamic)
	// length
	binary.BigEndian.PutUint64(buf[dynamicOffset+24:dynamicOffset+32], uint64(len(t.Denom)))
	dynamicOffset += 32

	// data
	copy(buf[dynamicOffset:], []byte(t.Denom))
	dynamicOffset += abi.Pad32(len(t.Denom))

	// Amount (static)

	if err := abi.EncodeBigInt(t.Amount, buf[32:64], false); err != nil {
		return 0, err
	}

	// Precision (static)
	buf[64+31] = byte(t.Precision)

	return dynamicOffset, nil
}

// Encode encodes DecCoin to ABI bytes
func (t DecCoin) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DecCoin from ABI bytes in the provided buffer
func (t *DecCoin) Decode(data0 []byte) error {
	if len(data0) < DecCoinStaticSize {
		return fmt.Errorf("insufficient data for DecCoin")
	}

	// Denom
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.Denom (dynamic)
		if offset+32 > len(data0) {
			return fmt.Errorf("insufficient data for length prefix")
		}
		length := int(binary.BigEndian.Uint64(data0[offset+24 : offset+32]))
		offset += 32
		// string data
		t.Denom = string(data0[offset : offset+length])
	}
	// t.Amount (static)
	t.Amount = new(big.Int).SetBytes(data0[32:64])
	// t.Precision (static)
	t.Precision = uint8(data0[64+31])

	return nil
}

const DummyCallStaticSize = 128

// DummyCall represents an ABI tuple
type DummyCall struct {
	A Coin
	B DecCoin
	C Dec
}

// EncodedSize returns the total encoded size of DummyCall
func (t DummyCall) EncodedSize() int {
	dynamicSize := 0

	dynamicSize += t.A.EncodedSize() // dynamic tuple
	dynamicSize += t.B.EncodedSize() // dynamic tuple

	return DummyCallStaticSize + dynamicSize
}

// EncodeTo encodes DummyCall to ABI bytes in the provided buffer
// it panics if the buffer is not large enough
func (t DummyCall) EncodeTo(buf []byte) (int, error) {
	dynamicOffset := DummyCallStaticSize // Start dynamic data after static section

	// A (offset)
	binary.BigEndian.PutUint64(buf[0+24:0+32], uint64(dynamicOffset))

	// A (dynamic)
	{
		n, err := t.A.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}

	// B (offset)
	binary.BigEndian.PutUint64(buf[32+24:32+32], uint64(dynamicOffset))

	// B (dynamic)
	{
		n, err := t.B.EncodeTo(buf[dynamicOffset:])
		if err != nil {
			return 0, err
		}
		dynamicOffset += n
	}
	// C (static)

	// Encode nested tuple t.C
	if _, err := t.C.EncodeTo(buf[64:]); err != nil {
		return 0, err
	}

	return dynamicOffset, nil
}

// Encode encodes DummyCall to ABI bytes
func (t DummyCall) Encode() ([]byte, error) {
	buf := make([]byte, t.EncodedSize())
	if _, err := t.EncodeTo(buf); err != nil {
		return nil, err
	}
	return buf, nil
}

// Decode decodes DummyCall from ABI bytes in the provided buffer
func (t *DummyCall) Decode(data0 []byte) error {
	if len(data0) < DummyCallStaticSize {
		return fmt.Errorf("insufficient data for DummyCall")
	}

	// A
	{
		offset := int(binary.BigEndian.Uint64(data0[0+24 : 0+32]))

		// t.A (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.A")
		}
		if err := t.A.Decode(data0[offset:]); err != nil {
			return err
		}
	}
	// B
	{
		offset := int(binary.BigEndian.Uint64(data0[32+24 : 32+32]))

		// t.B (dynamic)
		if offset >= len(data0) {
			return fmt.Errorf("insufficient data for dynamic data, t.B")
		}
		if err := t.B.Decode(data0[offset:]); err != nil {
			return err
		}
	}
	// t.C (static)
	if err := t.C.Decode(data0[64:128]); err != nil {
		return err
	}

	return nil
}

// EncodeWithSelector encodes dummy arguments to ABI bytes including function selector
func (t DummyCall) EncodeWithSelector() ([]byte, error) {
	result := make([]byte, 4+t.EncodedSize())
	copy(result[:4], DummySelector[:])
	if _, err := t.EncodeTo(result[4:]); err != nil {
		return nil, err
	}
	return result, nil
}
